# Anexo D: Listado completo del corpus {.unnumbered}

Este anexo presenta el listado de los 80 videos que conforman el corpus de la investigación, organizados por youtuber y orden cronológico de publicación. Para cada video se consigna el código interno de referencia (VID), el título, la fecha de publicación, la duración y el número de vistas al momento de la recolección de datos.

## Corpus completo (80 videos)

### Lucas Castel

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 1 | ESPECIAL DE HALLOWEEN | 31/10/2012 | 4:02 | 754K | [▶](https://www.youtube.com/watch?v=it54N3LuBSQ){target="_blank"} |
| 2 | VACACIONES EN LA PLAYA | 31/12/2012 | 4:42 | 1.5M | [▶](https://www.youtube.com/watch?v=oR31G9EOzDY){target="_blank"} |
| 3 | COMO EVITAR UN ROBO | LUCAS CASTEL | 5/2/2013 | 4:47 | 5.1M | [▶](https://www.youtube.com/watch?v=34PJFtnrJ0I){target="_blank"} |
| 4 | CASTEL RESPONDE #1 | 31/5/2013 | 3:34 | 848K | [▶](https://www.youtube.com/watch?v=UwkODpUobyo){target="_blank"} |
| 5 | 50 COSAS SOBRE MI | LUCAS CASTEL | 10/5/2014 | 5:21 | 2.4M | [▶](https://www.youtube.com/watch?v=Ld9er1BKrJw){target="_blank"} |
| 6 | EL MEJOR AÑO DE MI VIDA | LUCAS CASTEL | 23/12/2014 | 4:59 | 705K | [▶](https://www.youtube.com/watch?v=NkpGAc0uZc8){target="_blank"} |
| 7 | VIAJE EPICO A COLOMBIA con WEREVERTUMORRO | LUCAS CASTEL | 4/9/2015 | 7:40 | 1.2M | [▶](https://www.youtube.com/watch?v=Ut9lMnJ4Xo8){target="_blank"} |
| 8 | BAILO TWERKING CON MI HERMANO | CASTEL RESPONDE #7 | 13/11/2015 | 9:12 | 3.5M | [▶](https://www.youtube.com/watch?v=XrSxyScUZnM){target="_blank"} |
| 9 | PREGUNTAS INCOMODAS | DebRyanShow - Luisito Comunica - Mariano Bo | 16/4/2016 | 11:57 | 3.4M | [▶](https://www.youtube.com/watch?v=N4ihOcKMT_Y){target="_blank"} |
| 10 | VLOG VIAJE SECRETO A LONDRES | LUCAS CASTEL | 28/11/2016 | 7:31 | 663K | [▶](https://www.youtube.com/watch?v=O4fP6oz8zzk){target="_blank"} |

: Videos de Lucas Castel en el corpus (n=10). {.striped .hover}

### Julián Serrano

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 11 | FILOSOFANDO (? - Julian Serrano | 27/4/2012 | 7:00 | 382K | [▶](https://www.youtube.com/watch?v=vKUz7bOnQXA){target="_blank"} |
| 12 | Mi Pene ? :D - Julian Serrano | 9/5/2012 | 9:19 | 651K | [▶](https://www.youtube.com/watch?v=ovL9FQZGiPA){target="_blank"} |
| 13 | Draw My Life | Julian Serrano | 24/3/2013 | 5:43 | 12.2M | [▶](https://www.youtube.com/watch?v=rwQdY9jcZ-4){target="_blank"} |
| 14 | ¡ Julian Serrano Disfrazado ! :D | 8/10/2013 | 4:35 | 2.8M | [▶](https://www.youtube.com/watch?v=qMBA59C2IhI){target="_blank"} |
| 15 | NUNCA TE RINDAS | JULIAN SERRANO | 19/2/2014 | 3:32 | 513K | [▶](https://www.youtube.com/watch?v=4j1NAxPBofM){target="_blank"} |
| 16 | 1O personajes tipicos de la secundaria | 28/2/2014 | 6:33 | 546K | [▶](https://www.youtube.com/watch?v=0bMeK79RCTM){target="_blank"} |
| 17 | "Mi novia me maquilla" Pero ahora "ori me maquilla" | 1/1/2015 | 6:23 | 3.6M | [▶](https://www.youtube.com/watch?v=RT5YgaMBg8M){target="_blank"} |
| 18 | OLER PEDOS HACE BIEN PedosMilgrasos JULIAN SERRANO | 25/4/2015 | 8:03 | 5.1M | [▶](https://www.youtube.com/watch?v=WrGMjuAcG44){target="_blank"} |
| 19 | 02JS09 MI MAYOR MIEDO Con Tu Hermana JULIAN SERRANO | 30/9/2016 | 8:07 | 857K | [▶](https://www.youtube.com/watch?v=YMyPU3kbE54){target="_blank"} |
| 20 | viaje a mexico con otros creadores | 12/11/2016 | 11:16 | 545K | [▶](https://www.youtube.com/watch?v=OYXPpvwP2hw){target="_blank"} |

: Videos de Julián Serrano en el corpus (n=10). {.striped .hover}

### Gonzalo Fonseca

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 21 | SE DURMIÓ ?_? | 6/12/2012 | 2:52 | 1.6M | [▶](https://www.youtube.com/watch?v=4pQ-olkb8UQ){target="_blank"} |
| 22 | LAS EX NOVIAS by: Gonzaa Fonseca | 6/12/2012 | 2:49 | 227K | [▶](https://www.youtube.com/watch?v=Yz3BWP5JDVs){target="_blank"} |
| 23 | 0:02 / 3:41 YO TOMO AGUA MINERAL - Gonzaa Fonseca | 30/7/2013 | 3:42 | 378K | [▶](https://www.youtube.com/watch?v=cnqimWdJNf8){target="_blank"} |
| 24 | Preguntas Preguntosas 1 - Gonzaa Fonseca | 21/8/2013 | 4:49 | 149K | [▶](https://www.youtube.com/watch?v=Ztct3iGNBsk){target="_blank"} |
| 25 | PREGUNTAS 2 - Gonzaa Fonseca | 10/12/2014 | 7:12 | 5.0M | [▶](https://www.youtube.com/watch?v=N05Y_fwLm6k){target="_blank"} |
| 26 | RETOS - Gonzaa Fonseca | 21/8/2014 | 5:32 | 977K | [▶](https://www.youtube.com/watch?v=IviYE3B6v2s){target="_blank"} |
| 27 | BOTON DE PLATA Y EL #ClubMediaFest - Gonzaa Fonseca | 24/4/2015 | 9:20 | 402K | [▶](https://www.youtube.com/watch?v=BDl-IIY4ps8){target="_blank"} |
| 28 | PREGUNTAS INCOMODAS +18 Ft Julian Serrano y Julianero | 10/10/2015 | 13:10 | 2.1M | [▶](https://www.youtube.com/watch?v=Wtgi4dX9Gd4){target="_blank"} |
| 29 | APRENDER A TOMAR ALCOHOL - Gonzaa Fonseca | 17/1/2016 | 7:40 | 2.0M | [▶](https://www.youtube.com/watch?v=F9vuv1dLz9A){target="_blank"} |
| 30 | ME ESTAFARON | 31/1/2016 | 11:59 | 1.3M | [▶](https://www.youtube.com/watch?v=bWH-DlPR7Tg){target="_blank"} |

: Videos de Gonzalo Fonseca en el corpus (n=10). {.striped .hover}

### Lionel Ferro

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 31 | Ruggero Pasquarelli besa el pie de Lionel Ferro | #BesoDeRuggeEnE | 19/8/2016 | 11:20 | 8.2M | [▶](https://www.youtube.com/watch?v=iJHWDY3egSE){target="_blank"} |
| 32 | El reto del prrrr | Lionel Ferro y Agustín Bernasconi MYA | 30/10/2015 | 8:47 | 6.1M | [▶](https://www.youtube.com/watch?v=K9jBnc_b39k){target="_blank"} |
| 33 | LES PRESENTO AL AMOR DE MI VIDA | Lionel Ferro #NuevoVideoDeLio | 17/6/2016 | 11:21 | 3.0M | [▶](https://www.youtube.com/watch?v=QavLvIjAijk){target="_blank"} |
| 34 | Lio Ferro I MI PRIMERA VEZ #LioMiPrimeraVez | 19/2/2016 | 12:25 | 2.0M | [▶](https://www.youtube.com/watch?v=YoNiEDJKIK8){target="_blank"} |
| 35 | JUGANDO POKEMON GO! | Le cumpli el sueño a mi hermano | #LionelFe | 12/8/2016 | 9:03 | 1.5M | [▶](https://www.youtube.com/watch?v=gvMIa2J2KQg){target="_blank"} |
| 36 | El de Crepusculo se depila | 21/11/2014 | 3:09 | 291K | [▶](https://www.youtube.com/watch?v=TwmOPwhh6LA){target="_blank"} |
| 37 | Lionel Ferro | Challenge vergonzoso con mi amigo Santi. | 20/11/2015 | 8:23 | 282K | [▶](https://www.youtube.com/watch?v=JiEkVHrHl9U){target="_blank"} |
| 38 | Lionel Ferro | Mi amigo les cuenta secretos sobre mi | #AskLioyNi | 22/1/2016 | 6:14 | 268K | [▶](https://www.youtube.com/watch?v=fRWSiFUbd64){target="_blank"} |
| 39 | Lionel Ferro | Whisper Challenge | Qué escucho vs Qué dice | 2/1/2016 | 6:06 | 202K | [▶](https://www.youtube.com/watch?v=ByOWXPwBhi4){target="_blank"} |
| 40 | Las aventuras de Lionel Ferro en Snapchat | #Snapchat #LionelFerr | 24/8/2015 | 3:01 | 48K | [▶](https://www.youtube.com/watch?v=X8gruGj9lyo){target="_blank"} |

: Videos de Lionel Ferro en el corpus (n=10). {.striped .hover}

### Mariano Bondar

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 41 | MÚSICA,MODAS,JUSTINO BIVERO.. COSAS PASAJERAS | MARIANO BONDAR | 7/9/2012 | 6:25 | 333K | [▶](https://www.youtube.com/watch?v=8Pmq4GEN_aI){target="_blank"} |
| 42 | DÍAS SIN INTERNET | MARIANO BONDAR | 24/10/2013 | 6:32 | 520K | [▶](https://www.youtube.com/watch?v=tFjqBQn2O-w){target="_blank"} |
| 43 | FRUTA #1 - SAN MARTIN DE LOS ANDES | MARIANO BONDAR | 4/11/2013 | 7:10 | 1.6M | [▶](https://www.youtube.com/watch?v=IgMbSujZJFs){target="_blank"} |
| 44 | PREGUNTAME #2 | MARIANO BONDAR | 27/9/2014 | 4:30 | 911K | [▶](https://www.youtube.com/watch?v=zVbzEYmpwxY){target="_blank"} |
| 45 | 7 COSAS QUE HAGO CUANDO ESTOY ABURRIDO | MARIANO BONDAR | 15/3/2014 | 2:45 | 992K | [▶](https://www.youtube.com/watch?v=L_HMDebd0VQ){target="_blank"} |
| 46 | ESTE VIDEO NO TIENE SENTIDO | MARIANO BONDAR | 25/1/2015 | 2:54 | 494K | [▶](https://www.youtube.com/watch?v=wibQ67xnkMk){target="_blank"} |
| 47 | MIS PADRES ESTAN SEPARADOS | MARIANO BONDAR | 21/2/2015 | 5:05 | 689K | [▶](https://www.youtube.com/watch?v=NWXbWmQl-9w){target="_blank"} |
| 48 | FRUTA #2 - BARILOCHE | MARIANO BONDAR | 28/8/2015 | 9:15 | 1.7M | [▶](https://www.youtube.com/watch?v=h2TDv9wr4o8){target="_blank"} |
| 49 | MI PASADO OSCURO | MARIANO BONDAR | 8/1/2016 | 13:46 | 738K | [▶](https://www.youtube.com/watch?v=nIKmziznnT4){target="_blank"} |
| 50 | COMO SUPERÉ LA MUERTE DE MI AMIGO | MARIANO BONDAR | 15/4/2016 | 18:33 | 1.0M | [▶](https://www.youtube.com/watch?v=w-NRJl07Qgw){target="_blank"} |

: Videos de Mariano Bondar en el corpus (n=10). {.striped .hover}

### Gonzalo Goette

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 51 | DECLARACIÓN DE AMOR EN RECITAL / GONZALO GOETTE | 13/9/2015 | 3:23 | 905K | [▶](https://www.youtube.com/watch?v=LFdXBBHNr4w){target="_blank"} |
| 52 | BESANDO MUJERES FRENTE A SUS NOVIOS / GONZALO GOETTE | 13/1/2015 | 3:38 | 5.7M | [▶](https://www.youtube.com/watch?v=j64Lwp_rFZY){target="_blank"} |
| 53 | BESO O PATADA EN LAS BOLAS - GONZALO GOETTE | 27/10/2015 | 3:04 | 7.6M | [▶](https://www.youtube.com/watch?v=E7R7ITtAjNg){target="_blank"} |
| 54 | STRIPTEASE EN EL MC / GONZALO GOETTE | 21/12/2015 | 5:35 | 1.6M | [▶](https://www.youtube.com/watch?v=m-zCAg11tVs){target="_blank"} |
| 55 | VERDAD O BEBER / GONZALO GOETTE FT YAO CABRERA | 24/3/2016 | 10:38 | 1.7M | [▶](https://www.youtube.com/watch?v=fF1pGe0tIO4){target="_blank"} |
| 56 | TRIVIA DE HUEVOS GONZALO GOETTE FT GONZAA FONSECA NUEVO CANAL | 13/5/2016 | 7:18 | 1.2M | [▶](https://www.youtube.com/watch?v=Wzq5e_nb_IE){target="_blank"} |
| 57 | JUGANDO FUTBOL EN EL MC / GONZALO GOETTE FT YAO CABRERA Y TOMAS O | 1/7/2016 | 6:16 | 4.7M | [▶](https://www.youtube.com/watch?v=2mIXkcoo5dg){target="_blank"} |
| 58 | ¿LOS ARGENTINOS SOMOS HONESTOS? / GONZALO GOETTE FT. TOMAS ORANGE | 21/7/2016 | 7:40 | 13.9M | [▶](https://www.youtube.com/watch?v=7ijJI33n4X4){target="_blank"} |
| 59 | HACIENDO FELIZ A UN VAGABUNDO / GONZALO GOETTE | 29/8/2016 | 5:26 | 6.7M | [▶](https://www.youtube.com/watch?v=cmo_rxunSQU){target="_blank"} |
| 60 | MI HERMANITO TIENE NOVIA? RESPONDIENDO CON MI HERMANO / GONZALO G | 3/11/2016 | 11:04 | 3.6M | [▶](https://www.youtube.com/watch?v=DvCrgdSU-wQ){target="_blank"} |

: Videos de Gonzalo Goette en el corpus (n=10). {.striped .hover}

### Elchuiuical

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 61 | 07ji01 ESPECIAL 3000 SUSCRIPTORES #ElchuiucalResponde - EPIC VLOG | 3/3/2014 | 4:14 | 269K | [▶](https://www.youtube.com/watch?v=WqNW9XK3L1w){target="_blank"} |
| 62 | EL PEOR RAPERO DE LA HISTORIA | 10/10/2014 | 5:08 | 46K | [▶](https://www.youtube.com/watch?v=zISPGfL1h9I){target="_blank"} |
| 63 | BOTÓN DE PLATA DE YOUTUBE! - Especial 150,000 Suscriptor | 15/5/2015 | 4:33 | 6.1M | [▶](https://www.youtube.com/watch?v=MJtj0zSH9yU){target="_blank"} |
| 64 | SOY YUYA IMITANDO YOUTUBERS 2 | 24/6/2015 | 6:04 | 93K | [▶](https://www.youtube.com/watch?v=Zx9VUbrYqDk){target="_blank"} |
| 65 | VLOG EPICO: NIEVE, DON'T JUDGE ME CHALLENGE Y MÁS!! | 29/7/2015 | 5:14 | 1.5M | [▶](https://www.youtube.com/watch?v=AdgCNKX6wTo){target="_blank"} |
| 66 | TURRA AFEITÁNDOSE EL BIGOTE!! | 14/12/2015 | 6:31 | 151K | [▶](https://www.youtube.com/watch?v=9pFxgaP0VNo){target="_blank"} |
| 67 | SHOW EPICO!! (Ft. Youtubers) | 6/5/2016 | 4:32 | 4.0M | [▶](https://www.youtube.com/watch?v=WASEno-krn4){target="_blank"} |
| 68 | 50 COSAS SOBRE MI | 19/5/2016 | 6:27 | 241K | [▶](https://www.youtube.com/watch?v=DMCd6nL-E6U){target="_blank"} |
| 69 | HATER ME INSULTA!! | 28/6/2016 | 5:29 | 571K | [▶](https://www.youtube.com/watch?v=CKSU0HT_enw){target="_blank"} |
| 70 | DE FIESTA con YOUTUBERS en MEXICO!! | 17/11/2016 | 5:36 | 1.9M | [▶](https://www.youtube.com/watch?v=fT0hiHzx4hQ){target="_blank"} |

: Videos de Elchuiuical en el corpus (n=10). {.striped .hover}

### Mica Suárez

| VID | Título | Fecha | Duración | Vistas | Link |
|:--:|:---|:---|:--:|---:|:--:|
| 71 | 15 COSAS QUE ODIO - Mica Suarez | 9/12/2014 | 10:54 | 457K | [▶](https://www.youtube.com/watch?v=K2T0inAUkDY){target="_blank"} |
| 72 | PREGUNTAS DE TWITTER #1 - Mica Suarez | 3/1/2015 | 10:00 | 1.5M | [▶](https://www.youtube.com/watch?v=1claW_OqGQw){target="_blank"} |
| 73 | BOLUDA, VOY A IR A LA CÁRCEL! | Random #1: Boludeando - Mica Suar | 24/3/2015 | 11:14 | 258K | [▶](https://www.youtube.com/watch?v=PNkB2m-sM6Q){target="_blank"} |
| 74 | 50 COSAS SOBRE MI - Mica Suarez | 19/10/2015 | 16:28 | 630K | [▶](https://www.youtube.com/watch?v=muLDL_3EAyA){target="_blank"} |
| 75 | EL MEJOR VIAJE DE MI VIDA 1 - Mica Suarez | 19/11/2015 | 12:23 | 2.5M | [▶](https://www.youtube.com/watch?v=gOfg49BV_tI){target="_blank"} |
| 76 | ME ROBARON / SORTEO CELULAR (CERRADO)! - Mica Suarez | 25/12/2015 | 6:01 | 331K | [▶](https://www.youtube.com/watch?v=tFZsxfExb_o){target="_blank"} |
| 77 | EN OMEGLE HAY GENTE RARA - Mica Suarez | 18/10/2016 | 9:46 | 5.0M | [▶](https://www.youtube.com/watch?v=a_8qoaic-DM){target="_blank"} |
| 78 | MI CUENTA FANDOM - Mica Suarez | 10/12/2016 | 9:17 | 888K | [▶](https://www.youtube.com/watch?v=ZpisSvk0GrM){target="_blank"} |
| 79 | LA VERDAD DE BARBICA | 31/12/2016 | 9:38 | 3.2M | [▶](https://www.youtube.com/watch?v=sGkOnMgOTCg){target="_blank"} |
| 80 | 100K SORPRESA A USTEDES :D - Mica Suarez | 8/1/2016 | 6:08 | 2.2M | [▶](https://www.youtube.com/watch?v=Q-Dh6CzBYOk){target="_blank"} |

: Videos de Mica Suárez en el corpus (n=10). {.striped .hover}

## Estadísticas del corpus

| Métrica | Valor |
|:---|---:|
| Total de videos | 80 |
| Total de youtubers | 8 |
| Videos por youtuber | 10 |
| Duración total del corpus | 9h 39min |
| Duración promedio por video | 7:15 |
| Vistas acumuladas | 171.411.128 |
| Período cubierto | 2012–2016 |

: Estadísticas generales del corpus. {#tbl-estadisticas-corpus}