<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog – El videoblog como espacio social practicado: discursos, narrativas e identidades juveniles en YouTube Argentina (2012-2016)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06_trayectorias.html" rel="next">
<link href="./04_genero.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fa1ce29839742e4f64bd70bd814635ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="estilos.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_genero.html">Análisis y resultados</a></li><li class="breadcrumb-item"><a href="./05_identidades.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">El videoblog como espacio social practicado: discursos, narrativas e identidades juveniles en YouTube Argentina (2012-2016)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dedicatoria</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resumen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agradecimientos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Agradecimientos</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_mtya.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Marco Teórico y Antecedentes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_metod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Metodología</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Análisis y resultados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_genero.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">El videoblog como género ciberdiscursivo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_identidades.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_trayectorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trayectorias identitarias en el videoblog juvenil</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_lenguaje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Cierre</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Referencias Bibliográficas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias Bibliográficas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Anexos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_a_youtubers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo A: Youtubers del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_b_glosario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Anexo B: Glosario de términos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_c_corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo D: Listado completo del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_d_transcripciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo E: Transcripciones del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_e_materiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo F: Materiales de investigación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_f_topicmodeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo G: Modelado de tópicos — resultados explorativos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./indice_tematico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Índice temático</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">5.1</span> Introducción</a></li>
  <li><a href="#marco-conceptual" id="toc-marco-conceptual" class="nav-link" data-scroll-target="#marco-conceptual"><span class="header-section-number">5.2</span> Marco conceptual</a>
  <ul class="collapse">
  <li><a href="#representaciones-sociales-y-representaciones-discursivas" id="toc-representaciones-sociales-y-representaciones-discursivas" class="nav-link" data-scroll-target="#representaciones-sociales-y-representaciones-discursivas"><span class="header-section-number">5.2.1</span> Representaciones sociales y representaciones discursivas</a></li>
  <li><a href="#la-presentación-del-self-de-goffman-al-vlog" id="toc-la-presentación-del-self-de-goffman-al-vlog" class="nav-link" data-scroll-target="#la-presentación-del-self-de-goffman-al-vlog"><span class="header-section-number">5.2.2</span> La presentación del self: de Goffman al vlog</a></li>
  <li><a href="#culturas-juveniles-y-los-entre-generacionales" id="toc-culturas-juveniles-y-los-entre-generacionales" class="nav-link" data-scroll-target="#culturas-juveniles-y-los-entre-generacionales"><span class="header-section-number">5.2.3</span> Culturas juveniles y los “entre” generacionales</a></li>
  <li><a href="#el-modelo-integrado" id="toc-el-modelo-integrado" class="nav-link" data-scroll-target="#el-modelo-integrado"><span class="header-section-number">5.2.4</span> El modelo integrado</a></li>
  </ul></li>
  <li><a href="#representaciones-sociales-de-juventud-en-el-corpus" id="toc-representaciones-sociales-de-juventud-en-el-corpus" class="nav-link" data-scroll-target="#representaciones-sociales-de-juventud-en-el-corpus"><span class="header-section-number">5.3</span> Representaciones sociales de juventud en el corpus</a>
  <ul class="collapse">
  <li><a href="#representaciones-hegemónicas" id="toc-representaciones-hegemónicas" class="nav-link" data-scroll-target="#representaciones-hegemónicas"><span class="header-section-number">5.3.1</span> Representaciones hegemónicas</a></li>
  <li><a href="#representaciones-emergentes-y-contra-hegemónicas" id="toc-representaciones-emergentes-y-contra-hegemónicas" class="nav-link" data-scroll-target="#representaciones-emergentes-y-contra-hegemónicas"><span class="header-section-number">5.3.2</span> Representaciones emergentes y contra-hegemónicas</a></li>
  <li><a href="#tensiones-entre-representaciones" id="toc-tensiones-entre-representaciones" class="nav-link" data-scroll-target="#tensiones-entre-representaciones"><span class="header-section-number">5.3.3</span> Tensiones entre representaciones</a></li>
  </ul></li>
  <li><a href="#subjetividades-juveniles-de-la-teoría-a-la-operacionalización" id="toc-subjetividades-juveniles-de-la-teoría-a-la-operacionalización" class="nav-link" data-scroll-target="#subjetividades-juveniles-de-la-teoría-a-la-operacionalización"><span class="header-section-number">5.4</span> Subjetividades juveniles: de la teoría a la operacionalización</a>
  <ul class="collapse">
  <li><a href="#repertorio-de-subjetividades-disponibles" id="toc-repertorio-de-subjetividades-disponibles" class="nav-link" data-scroll-target="#repertorio-de-subjetividades-disponibles"><span class="header-section-number">5.4.1</span> Repertorio de subjetividades disponibles</a></li>
  <li><a href="#articulación-subjetividades-representaciones" id="toc-articulación-subjetividades-representaciones" class="nav-link" data-scroll-target="#articulación-subjetividades-representaciones"><span class="header-section-number">5.4.2</span> Articulación subjetividades × representaciones</a></li>
  </ul></li>
  <li><a href="#sistema-de-índices-ponderados" id="toc-sistema-de-índices-ponderados" class="nav-link" data-scroll-target="#sistema-de-índices-ponderados"><span class="header-section-number">5.5</span> Sistema de índices ponderados</a>
  <ul class="collapse">
  <li><a href="#justificación-metodológica" id="toc-justificación-metodológica" class="nav-link" data-scroll-target="#justificación-metodológica"><span class="header-section-number">5.5.1</span> Justificación metodológica</a></li>
  <li><a href="#índice-de-glocalidad-igl" id="toc-índice-de-glocalidad-igl" class="nav-link" data-scroll-target="#índice-de-glocalidad-igl"><span class="header-section-number">5.5.2</span> Índice de Glocalidad (IGL)</a></li>
  <li><a href="#índice-de-cercanía-parasocial-icp" id="toc-índice-de-cercanía-parasocial-icp" class="nav-link" data-scroll-target="#índice-de-cercanía-parasocial-icp"><span class="header-section-number">5.5.3</span> Índice de Cercanía Parasocial (ICP)</a></li>
  <li><a href="#índice-de-modulación-pasional-imp" id="toc-índice-de-modulación-pasional-imp" class="nav-link" data-scroll-target="#índice-de-modulación-pasional-imp"><span class="header-section-number">5.5.4</span> Índice de Modulación Pasional (IMP)</a></li>
  <li><a href="#índice-de-extimidad-iex" id="toc-índice-de-extimidad-iex" class="nav-link" data-scroll-target="#índice-de-extimidad-iex"><span class="header-section-number">5.5.5</span> Índice de Extimidad (IEX)</a></li>
  <li><a href="#índice-de-autenticidad-performativa-iap" id="toc-índice-de-autenticidad-performativa-iap" class="nav-link" data-scroll-target="#índice-de-autenticidad-performativa-iap"><span class="header-section-number">5.5.6</span> Índice de Autenticidad Performativa (IAP)</a></li>
  <li><a href="#resultados-generales-del-corpus" id="toc-resultados-generales-del-corpus" class="nav-link" data-scroll-target="#resultados-generales-del-corpus"><span class="header-section-number">5.5.7</span> Resultados generales del corpus</a></li>
  </ul></li>
  <li><a href="#estrategias-multimodales-de-construcción-subjetiva" id="toc-estrategias-multimodales-de-construcción-subjetiva" class="nav-link" data-scroll-target="#estrategias-multimodales-de-construcción-subjetiva"><span class="header-section-number">5.6</span> Estrategias multimodales de construcción subjetiva</a>
  <ul class="collapse">
  <li><a href="#el-cuerpo-como-texto-identitario" id="toc-el-cuerpo-como-texto-identitario" class="nav-link" data-scroll-target="#el-cuerpo-como-texto-identitario"><span class="header-section-number">5.6.1</span> El cuerpo como texto identitario</a></li>
  <li><a href="#geografías-de-la-autenticidad" id="toc-geografías-de-la-autenticidad" class="nav-link" data-scroll-target="#geografías-de-la-autenticidad"><span class="header-section-number">5.6.2</span> Geografías de la autenticidad</a></li>
  <li><a href="#la-música-de-las-emociones" id="toc-la-música-de-las-emociones" class="nav-link" data-scroll-target="#la-música-de-las-emociones"><span class="header-section-number">5.6.3</span> La música de las emociones</a></li>
  <li><a href="#combinaciones-y-modulaciones-subjetivas" id="toc-combinaciones-y-modulaciones-subjetivas" class="nav-link" data-scroll-target="#combinaciones-y-modulaciones-subjetivas"><span class="header-section-number">5.6.4</span> Combinaciones y modulaciones subjetivas</a></li>
  </ul></li>
  <li><a href="#análisis-multimodal-de-seis-videos-paradigmáticos" id="toc-análisis-multimodal-de-seis-videos-paradigmáticos" class="nav-link" data-scroll-target="#análisis-multimodal-de-seis-videos-paradigmáticos"><span class="header-section-number">5.7</span> Análisis multimodal de seis videos paradigmáticos</a>
  <ul class="collapse">
  <li><a href="#lucas-castel-50-cosas-sobre-mí-vid-5-la-intimidad-calibrada" id="toc-lucas-castel-50-cosas-sobre-mí-vid-5-la-intimidad-calibrada" class="nav-link" data-scroll-target="#lucas-castel-50-cosas-sobre-mí-vid-5-la-intimidad-calibrada"><span class="header-section-number">5.7.1</span> Lucas Castel, “50 COSAS SOBRE MÍ” (VID 5): la intimidad calibrada</a></li>
  <li><a href="#julián-serrano-draw-my-life-vid-13-la-biografía-espectacularizada" id="toc-julián-serrano-draw-my-life-vid-13-la-biografía-espectacularizada" class="nav-link" data-scroll-target="#julián-serrano-draw-my-life-vid-13-la-biografía-espectacularizada"><span class="header-section-number">5.7.2</span> Julián Serrano, “Draw My Life” (VID 13): la biografía espectacularizada</a></li>
  <li><a href="#mariano-bondar-como-superé-la-muerte-de-mi-amigo-vid-50-el-límite-de-la-extimidad" id="toc-mariano-bondar-como-superé-la-muerte-de-mi-amigo-vid-50-el-límite-de-la-extimidad" class="nav-link" data-scroll-target="#mariano-bondar-como-superé-la-muerte-de-mi-amigo-vid-50-el-límite-de-la-extimidad"><span class="header-section-number">5.7.3</span> Mariano Bondar, “COMO SUPERÉ LA MUERTE DE MI AMIGO” (VID 50): el límite de la extimidad</a></li>
  <li><a href="#mica-suárez-50-cosas-sobre-mí-vid-74-la-autenticidad-femenina" id="toc-mica-suárez-50-cosas-sobre-mí-vid-74-la-autenticidad-femenina" class="nav-link" data-scroll-target="#mica-suárez-50-cosas-sobre-mí-vid-74-la-autenticidad-femenina"><span class="header-section-number">5.7.4</span> Mica Suárez, “50 COSAS SOBRE MÍ” (VID 74): la autenticidad femenina</a></li>
  <li><a href="#gonzalo-goette-besando-mujeres-frente-a-sus-novios-vid-52-la-autenticidad-por-riesgo" id="toc-gonzalo-goette-besando-mujeres-frente-a-sus-novios-vid-52-la-autenticidad-por-riesgo" class="nav-link" data-scroll-target="#gonzalo-goette-besando-mujeres-frente-a-sus-novios-vid-52-la-autenticidad-por-riesgo"><span class="header-section-number">5.7.5</span> Gonzalo Goette, “BESANDO MUJERES FRENTE A SUS NOVIOS” (VID 52): la autenticidad por riesgo</a></li>
  <li><a href="#lionel-ferro-les-presento-al-amor-de-mi-vida-vid-33-la-autenticidad-profesionalizada" id="toc-lionel-ferro-les-presento-al-amor-de-mi-vida-vid-33-la-autenticidad-profesionalizada" class="nav-link" data-scroll-target="#lionel-ferro-les-presento-al-amor-de-mi-vida-vid-33-la-autenticidad-profesionalizada"><span class="header-section-number">5.7.6</span> Lionel Ferro, “LES PRESENTO AL AMOR DE MI VIDA” (VID 33): la autenticidad profesionalizada</a></li>
  <li><a href="#síntesis-comparativa" id="toc-síntesis-comparativa" class="nav-link" data-scroll-target="#síntesis-comparativa"><span class="header-section-number">5.7.7</span> Síntesis comparativa</a></li>
  </ul></li>
  <li><a href="#perfiles-identitarios-por-youtuber" id="toc-perfiles-identitarios-por-youtuber" class="nav-link" data-scroll-target="#perfiles-identitarios-por-youtuber"><span class="header-section-number">5.8</span> Perfiles identitarios por youtuber</a></li>
  <li><a href="#conclusiones-parciales" id="toc-conclusiones-parciales" class="nav-link" data-scroll-target="#conclusiones-parciales"><span class="header-section-number">5.9</span> Conclusiones parciales</a>
  <ul class="collapse">
  <li><a href="#hallazgos-estructurales" id="toc-hallazgos-estructurales" class="nav-link" data-scroll-target="#hallazgos-estructurales"><span class="header-section-number">5.9.1</span> Hallazgos estructurales</a></li>
  <li><a href="#articulación-entre-lo-teórico-y-lo-empírico" id="toc-articulación-entre-lo-teórico-y-lo-empírico" class="nav-link" data-scroll-target="#articulación-entre-lo-teórico-y-lo-empírico"><span class="header-section-number">5.9.2</span> Articulación entre lo teórico y lo empírico</a></li>
  <li><a href="#identidades-como-montajes-afectivos-multimodales" id="toc-identidades-como-montajes-afectivos-multimodales" class="nav-link" data-scroll-target="#identidades-como-montajes-afectivos-multimodales"><span class="header-section-number">5.9.3</span> Identidades como montajes afectivos multimodales</a></li>
  <li><a href="#condiciones-de-posibilidad-y-límites-estructurales" id="toc-condiciones-de-posibilidad-y-límites-estructurales" class="nav-link" data-scroll-target="#condiciones-de-posibilidad-y-límites-estructurales"><span class="header-section-number">5.9.4</span> Condiciones de posibilidad y límites estructurales</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_genero.html">Análisis y resultados</a></li><li class="breadcrumb-item"><a href="./05_identidades.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">5.1</span> Introducción</h2>
<p>En el capítulo anterior se caracterizó al videoblog como un género ciberdiscursivo que responde a necesidades comunicativas específicas de las juventudes contemporáneas. Se analizaron su estructura multimodal, su encuadre comunitario y las formas en que la interfaz de la plataforma moldea y restringe lo que es discursivamente posible. Ahora el análisis da un paso más: si el capítulo anterior preguntaba <em>cómo se estructura el género</em>, este pregunta <em>qué se hace con él</em>. La pregunta central que lo organiza es: ¿cómo construyen y negocian su identidad los jóvenes youtubers argentinos en el videoblog de YouTube?</p>
<p>Entendemos estas identidades no como esencias previas que los sujetos “expresan” en la plataforma, sino como prácticas discursivas multimodales situadas que se producen, negocian y transforman en la intersección entre lo individual y lo colectivo, lo emocional y lo reflexivo, lo local y lo global. Las identidades juveniles en el vlog emergen como narrativas afectivas construidas mediante la selección y articulación de episodios vitales “narrables” <span class="citation" data-cites="labov1972">(<a href="referencias.html#ref-labov1972" role="doc-biblioref">Labov, 1972</a>)</span>, que responden tanto a las lógicas biográficas del sujeto como a las condiciones de la plataforma: algoritmos, métricas de visibilidad, feedback de audiencias y representaciones circulantes sobre lo juvenil. Estas condiciones no son neutrales: como señalan <span class="citation" data-cites="vandijck2018">Dijck et al. (<a href="referencias.html#ref-vandijck2018" role="doc-biblioref">2018, p. 4</a>)</span>, las plataformas son “infraestructuras digitales programables que organizan las interacciones entre usuarios” mediante mecanismos de dataficación, mercantilización y selección algorítmica que moldean las posibilidades de lo decible y lo visible. La identidad del youtuber se construye, entonces, no solo <em>en</em> la plataforma, sino <em>con</em> y <em>contra</em> ella.</p>
<p>El análisis se organiza en tres niveles articulados. El <strong>nivel estructural</strong> corresponde a las representaciones sociales de juventud como marcos de posibilidad y restricción discursiva. El <strong>nivel interaccional</strong> corresponde a las subjetividades como modos situados de transitar y encarnar esas representaciones. El <strong>nivel narrativo</strong> corresponde a las identidades como montajes discursivos que articulan fragmentos biográficos mediante hilos conductores afectivos y temáticos. La hipótesis que los articula es que las identidades juveniles digitales en el videoblog se construyen como montajes narrativos afectivos multimodales, moldeados tanto por las decisiones reflexivas del enunciador como por las condiciones simbólicas y técnicas de la plataforma, y sostenidos por la modulación pasional como hilo conductor que les otorga coherencia biográfica y reconocimiento comunitario.</p>
</section>
<section id="marco-conceptual" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="marco-conceptual"><span class="header-section-number">5.2</span> Marco conceptual</h2>
<section id="representaciones-sociales-y-representaciones-discursivas" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="representaciones-sociales-y-representaciones-discursivas"><span class="header-section-number">5.2.1</span> Representaciones sociales y representaciones discursivas</h3>
<p>El concepto de representaciones sociales (RS), formulado por <span class="citation" data-cites="moscovici1979">Moscovici (<a href="referencias.html#ref-moscovici1979" role="doc-biblioref">1984</a>)</span>, constituye un punto de partida conceptual productivo para comprender cómo los sujetos construyen conocimiento de sentido común. Moscovici definió una representación social como “una modalidad particular de conocimiento cuya función es la elaboración de los comportamientos y la comunicación entre los individuos” (p.&nbsp;17-18). Las RS funcionan como marcos interpretativos compartidos que hacen posible la vida social al proveer códigos comunes de significación; operan mediante dos procesos: la <em>objetivación</em>, que otorga textura material a nociones abstractas, y el <em>anclaje</em>, que integra lo nuevo en un sistema de conocimiento preexistente <span class="citation" data-cites="jodelet1986">(<a href="referencias.html#ref-jodelet1986" role="doc-biblioref">Jodelet, 1984</a>)</span>.</p>
<p>Para nuestro análisis del ciberdiscurso juvenil resulta particularmente productiva la articulación que propone <span class="citation" data-cites="raiter2002"><span class="nocase">Raiter et al.</span> (<a href="referencias.html#ref-raiter2002" role="doc-biblioref">2002</a>)</span> entre representaciones sociales y representaciones discursivas. Las RS tienen una dimensión cognitiva, pero solo podemos acceder a ellas a través de sus materializaciones discursivas: en el caso de los videoblogs, las representaciones sobre juventud no simplemente “se expresan” en los videos, sino que se construyen performativamente en cada enunciación. En este desplazamiento desde la RS a la Representación Discursiva (RD), seguimos a <span class="citation" data-cites="montecinosoto2005">Montecino Soto (<a href="referencias.html#ref-montecinosoto2005" role="doc-biblioref">2005</a>)</span>, quien las define como las “imágenes-creencias” que los hablantes construyen lingüísticamente en contextos concretos mediante recursos léxicos, semánticos y sintácticos.</p>
</section>
<section id="la-presentación-del-self-de-goffman-al-vlog" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="la-presentación-del-self-de-goffman-al-vlog"><span class="header-section-number">5.2.2</span> La presentación del self: de Goffman al vlog</h3>
<p>La teoría dramatúrgica de <span class="citation" data-cites="goffman1959">Goffman (<a href="referencias.html#ref-goffman1959" role="doc-biblioref">1959</a>)</span> ofrece herramientas centrales para comprender las dinámicas identitarias en el vlog. Los conceptos son conocidos, pero vale la pena precisar cómo operan en el medio digital.</p>
<p>La <strong>fachada</strong> (<em>front</em>) en el videoblog incluye el escenario de grabación, la apariencia, y los modales del youtuber frente a la cámara. La distinción entre <strong><em>frontstage</em></strong> y <strong><em>backstage</em></strong> se complejiza porque los youtubers graban frecuentemente en espacios privados —el dormitorio como espacio <em>backstage</em> por excelencia— y exhiben deliberadamente elementos de esa región posterior como estrategia de autenticidad. La edición permite controlar qué del backstage se revela, lo que genera lo que podríamos llamar un <em>backstage curado</em>: la exhibición de lo supuestamente espontáneo es, ella misma, un trabajo de producción.</p>
<p>Esta lógica conecta directamente con lo que <span class="citation" data-cites="sibilia2008">Sibilia (<a href="referencias.html#ref-sibilia2008" role="doc-biblioref">2008</a>)</span> denominó <strong><em>extimidad</em></strong>: la exhibición estratégica de la intimidad como forma de construcción del yo en entornos de alta visibilidad. Ver un videoblog confesional no es leer el diario ajeno: es estar sentado en la habitación de alguien mientras te cuenta sus secretos mirándote a los ojos. Sin embargo, esos ojos están mirando a una cámara, y ese cuarto fue elegido, preparado, iluminado. La asimetría técnica del medio no destruye el efecto emocional de la extimidad —lo hace posible. La aplicación de Goffman al entorno digital requiere considerar las especificidades del medium: asincronía (que permite edición y control), escalabilidad (audiencia potencialmente masiva), persistencia (archivo de actuaciones) y replicabilidad (videos compartidos y resignificados).</p>
</section>
<section id="culturas-juveniles-y-los-entre-generacionales" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="culturas-juveniles-y-los-entre-generacionales"><span class="header-section-number">5.2.3</span> Culturas juveniles y los “entre” generacionales</h3>
<p>El concepto de culturas juveniles, desarrollado por <span class="citation" data-cites="feixa1998">Feixa P‘ampols (<a href="referencias.html#ref-feixa1998" role="doc-biblioref">1998</a>)</span> y <span class="citation" data-cites="feixa2014">Feixa (<a href="referencias.html#ref-feixa2014" role="doc-biblioref">2014</a>)</span>, resulta fundamental para comprender las identidades que se construyen en el videoblog. Feixa define las culturas juveniles como “el conjunto de formas de vida y valores, expresados por colectivos generacionales en respuesta a sus condiciones de existencia social y material” (1998, p.&nbsp;60). Esta definición enfatiza que lo juvenil no es una categoría biológica, sino una construcción sociocultural históricamente situada.</p>
<p>Para el análisis específico de nuestro corpus resultan particularmente productivos los aportes de <span class="citation" data-cites="bernete2007">Bernete (<a href="referencias.html#ref-bernete2007" role="doc-biblioref">2007</a>)</span>, quien considera que las culturas juveniles de la primera década del siglo XXI “habitan el ‘entre’”. Identifica cinco: entre la pertenencia a la cultura global y el refugio en las culturas locales; entre la vinculación a otros jóvenes y la reproducción del mundo adulto; entre la comunicación de masas y la comunicación en red; entre el mandato de obedecer y el mandato de distinguirse; entre la escuela obligatoria y la escuela desbordada.</p>
<p>Estos “entre” no son tensiones abstractas, sino coordenadas estructurales que se materializan en prácticas discursivas concretas. Cuando Lucas Castel hace un video de Halloween usando un formato global, pero explicando que “en Argentina la gente mayor no tiene idea de lo que es Halloween” (VID 1), está habitando productivamente el entre global/local. Cuando Julián Serrano construye su identidad rebelde, pero simultáneamente apela a experiencias compartidas con su audiencia joven, está negociando entre distinguirse y pertenecer. A su vez, <span class="citation" data-cites="bernete2007">Bernete (<a href="referencias.html#ref-bernete2007" role="doc-biblioref">2007</a>)</span> señala que Internet ha recuperado la palabra, pero que los jóvenes siguieron decantando por opciones más emotivas: el vlog “ha traído a la blogsfera la experiencia no verbal: intercambio de imágenes, fijas o en movimiento, con sonido o sin él, pero sin texto que cuente algo, haciendo que el sentido dependa mucho más de quien lo recibe y sus circunstancias” (p.&nbsp;69). Lo que nos importa de este señalamiento es que el vlog no resuelve los “entre” sino que los convierte en materia prima narrativa.</p>
<p>El diseño de nuestra matriz de análisis operacionalizó estos planteos teóricos mediante pares de oposición que permitieron registrar cómo las identidades juveniles se discursivan en la tensión entre polos aparentemente contradictorios: Global/Local, Mundo joven/Mundo adulto, Comunicación en redes/Comunicación en masas, Obedecer/Distinguirse. Como señala <span class="citation" data-cites="garciacanclini1989">García Canclini (<a href="referencias.html#ref-garciacanclini1989" role="doc-biblioref">1995</a>)</span> en su conceptualización de las culturas híbridas, no se trata de procesos de sustitución, sino de entrecruzamiento.</p>
</section>
<section id="el-modelo-integrado" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="el-modelo-integrado"><span class="header-section-number">5.2.4</span> El modelo integrado</h3>
<p>Proponemos un modelo analítico que articula tres niveles complementarios: las representaciones sociales como marcos estructurantes que delimitan lo pensable, decible y mostrable sobre juventud; las subjetividades como repertorios de posiciones disponibles para los sujetos dentro de esos marcos; y las identidades narrativas como las construcciones específicas que cada youtuber elabora articulando selectivamente elementos de los niveles anteriores mediante hilos narrativos que otorgan coherencia biográfica.</p>
<div id="fig-modelo-niveles" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-modelo-niveles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imagenes/viz19_modelo_niveles.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-modelo-niveles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.1: Modelo analítico integrado: tres niveles de análisis de las identidades juveniles digitales. El videoblog actúa como arena de negociación entre representaciones, subjetividades e identidades.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📊 Código fuente de esta visualización
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Esta figura fue generada con el script <a href="scripts/viz_all.py"><code>viz_all.py</code></a>. Los datos provienen de <code>MATRIZ_FINAL_RESTAURADA.csv</code> (corpus: 80 videoblogs).</p>
</div>
</div>
</div>
</section>
</section>
<section id="representaciones-sociales-de-juventud-en-el-corpus" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="representaciones-sociales-de-juventud-en-el-corpus"><span class="header-section-number">5.3</span> Representaciones sociales de juventud en el corpus</h2>
<p>Esta sección examina las representaciones sobre juventud que circulan, se reproducen y se negocian en los videoblogs del corpus. Como señala <span class="citation" data-cites="palazzo2010b">Palazzo (<a href="referencias.html#ref-palazzo2010b" role="doc-biblioref">2009</a>)</span>, el ciberdiscurso juvenil no solo refleja representaciones preexistentes, sino que las construye, las actualiza y las pone en tensión mediante prácticas discursivas específicas.</p>
<p>Para identificar las representaciones operantes en el corpus se aplicó un enfoque mixto. El análisis temático de las matrices de codificación relevó sistemáticamente los 80 videos identificando patrones relacionados con construcciones identitarias. Las variables más directamente vinculadas a representaciones de juventud son: “Identidad y subjetividad” (45/80 videos = 56.25%), “Extimidad e intimidad compartida” (32/80 = 40%), “Familia y vínculos afectivos” (28/80 = 35%), “Amor, pareja y sexualidad” (24/80 = 30%), “Glocalidad y referencias culturales” (48/80 = 60%). El análisis léxico-semántico de las 80 transcripciones disponibles identificó campos semánticos recurrentes. La codificación siguió criterios binarios (presencia/ausencia) para cada video; las categorías no son mutuamente excluyentes, permitiendo co-ocurrencias que revelan articulaciones complejas. Los índices ponderados que se presentan más adelante complementan este análisis binario al capturar gradaciones e intensidades.</p>
<section id="representaciones-hegemónicas" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="representaciones-hegemónicas"><span class="header-section-number">5.3.1</span> Representaciones hegemónicas</h3>
<p>Del análisis emergen cuatro grandes representaciones sobre juventud que estructuran las narrativas identitarias de los youtubers argentinos.</p>
<section id="los-jóvenes-como-residentes-digitales-creativos" class="level4" data-number="5.3.1.1">
<h4 data-number="5.3.1.1" class="anchored" data-anchor-id="los-jóvenes-como-residentes-digitales-creativos"><span class="header-section-number">5.3.1.1</span> Los jóvenes como residentes digitales creativos</h4>
<p>Un 68% de los videos contienen referencias a competencias digitales o creatividad mediática. Esta representación se caracteriza por la naturalización del manejo tecnológico, la creatividad como valor diferenciador generacional, y el emprendedurismo digital como alternativa laboral legítima.</p>
<p>El ejemplo paradigmático es el video “VLOG VIAJE SECRETO A LONDRES” de Lucas Castel (VID 10). Al narrar su viaje a las instalaciones de YouTube en Londres, donde fue seleccionado por la plataforma entre creadores de contenido, dice:</p>
<blockquote class="blockquote">
<p>“Me llegó una noticia de YouTube, me eligieron para ir a Londres. La verdad que Londres es un lugar hermoso, es un lugar que siempre quise conocer. Y ahora se me dio la oportunidad, así que bueno, gracias a ustedes que me apoyan, a YouTube que me eligió por alguna razón, así que estoy muy feliz.” (0:17-0:30)</p>
</blockquote>
<p>La frase “YouTube me eligió” construye una narrativa meritocrática donde la plataforma reconoce y premia el talento creativo juvenil. El viaje a Londres funciona como validación institucional de su estatus de creador. Significativamente, Lucas no presenta esto como logro excepcional, sino como consecuencia natural de su trayectoria, naturalizando la figura del youtuber como profesional legítimo.</p>
<p>Gonzalo Fonseca introduce un matiz reflexivo al documentar la recepción del “botón de plata” en “BOTÓN DE PLATA Y EL #ClubMediaFest” (VID 27):</p>
<blockquote class="blockquote">
<p>“Es por haber pasado los 100.000 suscriptores. Tipo, ya voy por los 300.000, ¿no? Pero YouTube es medio lento. Estoy zarpado que te manden estas cosas. […] Nada más quería mostrarles, porque esto lo logré gracias a ustedes.” (0:07-0:31)</p>
</blockquote>
<p>Y más adelante, al describir el evento presencial:</p>
<blockquote class="blockquote">
<p>“Si aún no se da cuenta de la magnitud de gente que te ve hasta que ves a toda esa gente ahí… ¡La puta madre! ¡30.000 personas, papá!” (1:25-1:42)</p>
</blockquote>
<p>El botón de plata funciona como objeto-fetiche que materializa el reconocimiento institucional; la expresión “cumplir todos mis sueños” explicita la narrativa aspiracional que subyace a esta representación.</p>
<p>Sin embargo, la representación del “joven creador digital” no es unívoca. Elchuiuical (VID 63) introduce la tensión entre el crecimiento del canal y la expectativa de cercanía comunitaria:</p>
<blockquote class="blockquote">
<p>“También me molesta que mucha gente diga que cambié de corazón. […] No puedo responder los comentarios que respondía cuando tenía 5.000.” (1:53-2:05)</p>
</blockquote>
<p>Al defender la legitimidad de una gestión profesionalizada que no puede mantener las mismas prácticas de cuando el canal era pequeño, Elchuiuical demuestra que la representación está atravesada por una demanda contradictoria: el creador debe ser a la vez profesional y cercano.</p>
</section>
<section id="la-juventud-como-momento-de-libertad-y-experimentación" class="level4" data-number="5.3.1.2">
<h4 data-number="5.3.1.2" class="anchored" data-anchor-id="la-juventud-como-momento-de-libertad-y-experimentación"><span class="header-section-number">5.3.1.2</span> La juventud como momento de libertad y experimentación</h4>
<p>Un 72% de los videos incluyen narrativas de libertad, rebeldía o experimentación. La reivindicación del derecho a equivocarse, la exploración identitaria como proceso legítimo y la tensión con las expectativas adultas caracterizan esta representación.</p>
<p>Julián Serrano la despliega en “FILOSOFANDO (?)” (VID 11) con una complejidad irónica que merece atención:</p>
<blockquote class="blockquote">
<p>“Antes hacía videos, lo hacía porque estaba re al pedo en la secundaria y no hacía nada, ahora hago algo y la verdad que no estoy tan al pedo como a mí me gustaría estar, así que decidí una cosa, y esta, presta atención que es muy buena y yo sé que yo tengo mucha llegada al público joven de Argentina, soy como un ejemplo a seguir, aunque sea la peor mierda para seguir, me tomás como un ejemplo, lo cual me parece pésimo, pero bueno, ahí va, dejo la facultad.” (0:48-1:08)</p>
</blockquote>
<p>El fragmento es notable en varios niveles. Serrano se posiciona simultáneamente como “ejemplo a seguir” y como “la peor mierda para seguir”, desactivando la autoridad que él mismo construye. La decisión de dejar la facultad, sancionada negativamente por la lógica adulta, se presente como acto de autonomía. El título interrogativo “FILOSOFANDO (?)” refuerza la distancia irónica: la reflexión existencial se presenta como juego. En contraste, en “NUNCA TE RINDAS” (VID 15) Serrano adopta un registro claramente motivacional:</p>
<blockquote class="blockquote">
<p>“¿O querés ser uno más? ¿Querés ser otra estadística del número de personas que no hicieron lo que querían por el miedo a qué dirán, que no caminan por miedo a que los perros ladren?” (1:02-1:10)</p>
</blockquote>
<p>La metáfora de “los perros que ladran” codifica a los críticos como adultos o instituciones que intentan detener la autorrealización juvenil.</p>
<p>Una versión más cotidiana y menos épica de esta representación aparece en Mica Suárez (VID 71, “15 COSAS QUE ODIO”), donde la autonomía se construye en el terreno de lo doméstico y lo estético:</p>
<blockquote class="blockquote">
<p>“Odio a las personas materialistas. […] A mí me pasó mucho con estos auriculares. Sí, son una mierda. Simulan ser Beats, pero obviamente no son originales. No se imaginan la cantidad de personas que me cargaron por tener estos auriculares.” (1:24-1:46)</p>
</blockquote>
<p>Mica reivindica el derecho a usar auriculares “truchos” sin vergüenza. Esta rebeldía menor, cotidiana y “no épica”, es característica del registro de varios youtubers del corpus, donde la autonomía se articula desde lo estético más que desde grandes gestos de ruptura.</p>
</section>
<section id="el-youtuber-como-trabajo-legítimo" class="level4" data-number="5.3.1.3">
<h4 data-number="5.3.1.3" class="anchored" data-anchor-id="el-youtuber-como-trabajo-legítimo"><span class="header-section-number">5.3.1.3</span> El youtuber como trabajo legítimo</h4>
<p>Un 45% de los videos incluyen referencias a YouTube como trabajo o profesión. La defensa frente a críticas adultas, la profesionalización de la práctica y la construcción de autoridad desde competencias digitales caracterizan esta representación.</p>
<p>Lucas Castel la articula de manera paradigmática en “EL MEJOR AÑO DE MI VIDA” (VID 6):</p>
<blockquote class="blockquote">
<p>“Por más que vos digas que soy un virgen que está solo en una habitación hablándole a una cámara, no es así. Porque no le estoy hablando a una cámara, le estoy hablando a ustedes. A los que están ahí mirándome.” (0:33-0:45)</p>
</blockquote>
<p>Al reformular la actividad de producción solitaria de contenido como práctica comunicativa relacional, Lucas transforma la imagen del youtuber solitario en productor de comunidad. Y más adelante en el mismo video, narra la génesis de esa práctica con una transparencia que ilumina la lógica del oficio:</p>
<blockquote class="blockquote">
<p>“Hace tiempo cuando yo empecé a hacer videos, me acuerdo que mis amigos y los pocos que me miraban me decían que lo que hacía estaba bueno y que lo siga haciendo. Yo dije, bueno, está bien, si les gusta y le alegro el día a alguien, ¿por qué no? Lo sigo haciendo. Seguí haciendo videos, seguí cagándome de risa y bueno, el tiempo fue pasando hasta que pasó.” (VID 6, 0:09-0:20)</p>
</blockquote>
<p>El relato es significativo: la motivación no es la fama ni el dinero, sino el reconocimiento de los pares y la posibilidad de “alegrar el día a alguien”. La frase final —“el tiempo fue pasando hasta que pasó”— naturaliza el crecimiento del canal como algo que simplemente <em>ocurrió</em>, no como un proyecto estratégico. La anticipación y refutación de la crítica (“vas a ser un agrandado”) evidencia la conciencia de que esta representación se construye activamente, no se da por sentada.</p>
</section>
<section id="autenticidad" class="level4" data-number="5.3.1.4">
<h4 data-number="5.3.1.4" class="anchored" data-anchor-id="autenticidad"><span class="header-section-number">5.3.1.4</span> Autenticidad</h4>
<p>Un 82% de los videos incluyen marcadores de autenticidad, convirtiendo a ésta en la representación más extendida del corpus. El imperativo de “ser uno mismo”, la transparencia emocional como prueba de genuinidad y el rechazo a la hipocresía la caracterizan.</p>
<p>El formato “50 cosas sobre mí” funciona como tecnología de autenticidad. Lucas Castel lo establece desde el comienzo (VID 5): “Así me conocerán un poquito más y saben quién carajo soy, ¿no?” La expresión es deliberadamente zafada, pero también directa: la autenticidad se produce revelando información personal que construye familiaridad.</p>
<p>Sin embargo, lo que se revela es cuidadosamente calibrado. Después de contar que come budín mientras se baña (excentricidad menor que construye autenticidad mediante la absurdidad), señala: “Tuve solamente una novia y estoy soltero hace rato. Y la verdad se vive muy bien así, papá” (1:20-1:26). El comentario jocoso inmediatamente deflecta el potencial dramatismo del tema. Esta oscilación entre revelación e ironía es característica del estilo de Lucas: permite intimidad calibrada sin exposición excesiva.</p>
<p>Mica Suárez despliega una versión de autenticidad específicamente generizada en VID 74: “Casi nunca me maquillo. Prefiero estar diez mil veces así, al natural, y que me vean así como soy. Sin filtro.” Y agrega: “Cuando era chica me hacían mucho bullying. Demasiado. Vivía en una provincia y me insultaban mucho por ser de Buenos Aires. O sea, por ser porteña. Pero bueno, son cosas que pasan. Y me pasan a mí sola.” El “sin filtro” opera en doble sentido: literal (sin maquillaje) y metafórico (sin censura). La frase final —“son cosas que pasan, y me pasan a mí sola”— combina resignación con reivindicación de singularidad: su experiencia es a la vez universal y única.</p>
<p>Elchuiuical (VID 68) construye autenticidad mediante la acumulación de detalles ordinarios y el humor autodeprecativo: “Vivo en Bahía Blanca, que es una ciudad al sur de la provincia de Buenos Aires. Y es una ciudad, no es un pueblo. No inventen que es un pueblo porque viven como 400.000 personas. No hay vacas, hay wifi.” Y sobre ser prematuro: “Por eso que soy tan retrasado.” Su autenticidad reside en no tomarse en serio, en la negativa a construir una imagen heroica.</p>
<p>Como argumenta <span class="citation" data-cites="marwick2013">Marwick (<a href="referencias.html#ref-marwick2013" role="doc-biblioref">2013</a>)</span>, la autenticidad en redes sociales no consiste en la ausencia de performance, sino en la capacidad de construir performances que sean percibidas como genuinas. La autenticidad digital es una autenticidad performada, pero no por ello menos real en sus efectos identitarios y comunitarios.</p>
</section>
</section>
<section id="representaciones-emergentes-y-contra-hegemónicas" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="representaciones-emergentes-y-contra-hegemónicas"><span class="header-section-number">5.3.2</span> Representaciones emergentes y contra-hegemónicas</h3>
<p>Junto a las representaciones dominantes, el corpus evidencia representaciones que cuestionan o complejizan las visiones hegemónicas. No son marginales: aparecen de manera consistente en aproximadamente un tercio del corpus.</p>
<section id="la-juventud-vulnerable" class="level4" data-number="5.3.2.1">
<h4 data-number="5.3.2.1" class="anchored" data-anchor-id="la-juventud-vulnerable"><span class="header-section-number">5.3.2.1</span> La juventud vulnerable</h4>
<p>Un 28% de los videos incluyen referencias explícitas a vulnerabilidad, ansiedad o problemas emocionales. Mariano Bondar es el caso más representativo. En “COMO SUPERÉ LA MUERTE DE MI AMIGO” (VID 50) abre así:</p>
<blockquote class="blockquote">
<p>“Hace mucho tiempo que tengo ganas de hacer este video y bueno, recientemente no me he estado sintiendo muy bien y bueno, como siempre tengo la cámara como para poder descargarme. No tengo idea cuándo subir este video, no tengo idea siquiera si voy a avisar que voy a subir este video, pero es algo que tengo muchas ganas de compartir hace tiempo.” (0:08-0:35)</p>
</blockquote>
<p>La incertidumbre sobre la publicación es significativa: rompe la lógica de producción regular del youtuber y marca que este contenido excede las categorías habituales. La referencia a la cámara como herramienta de descarga emocional explicita una función del videoblog que usualmente permanece implícita. En el mismo video, describe las consecuencias psicológicas de la pérdida de su amigo:</p>
<blockquote class="blockquote">
<p>“Después de eso creo que vino una de las peores partes de mi adolescencia […] atravesé una grandísima depresión […] que me hizo muchas veces no ir al colegio, que me hacía no comer, que me hacía querer estar solo.” (5:20-6:01)</p>
</blockquote>
<p>La mención explícita de “depresión” como diagnóstico, junto con síntomas concretos, constituye una revelación de salud mental que excede significativamente los niveles habituales de exposición en el videoblog juvenil. Como señala <span class="citation" data-cites="feixa2014">Feixa (<a href="referencias.html#ref-feixa2014" role="doc-biblioref">2014</a>)</span>, las generaciones digitales enfrentan formas específicas de precariedad y ansiedad vinculadas a la hiperconectividad y las demandas de autogestión identitaria en entornos de alta visibilidad.</p>
<div id="fig-bondar-vulnerabilidad" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bondar-vulnerabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="capturas/cap05_c01_bondar_vulnerabilidad.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bondar-vulnerabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.2: Performance de la vulnerabilidad: el youtuber como sujeto sensible que comparte sus angustias y fragilidades para construir un vínculo de autenticidad con su audiencia (Mariano Bondar, 2016).
</figcaption>
</figure>
</div>
<p><a href="https://youtu.be/0-nZidrR17w?si=3E5C77uE32fMv0C5&amp;t=150" target="_blank">▶ Ver este momento en YouTube</a></p>
</section>
<section id="el-fracaso-como-parte-del-proceso" class="level4" data-number="5.3.2.2">
<h4 data-number="5.3.2.2" class="anchored" data-anchor-id="el-fracaso-como-parte-del-proceso"><span class="header-section-number">5.3.2.2</span> El fracaso como parte del proceso</h4>
<p>Un 22% de los videos tematizan fracasos, errores o dificultades de manera explícita. Algunos youtubers narran sus fracasos previos, videos que “no funcionaron” o momentos de desánimo, construyendo una imagen más compleja y realista de la trayectoria del creador digital. Esta representación opera en tres niveles: desmitificación del éxito instantáneo, valorización del proceso sobre el resultado, y construcción de resiliencia como valor juvenil. Al mostrar que el camino hacia la visibilidad digital incluye tropiezos, los youtubers construyen narrativas de autenticidad que los diferencian de las imágenes idealizadas del éxito que circulan en otros medios.</p>
</section>
</section>
<section id="tensiones-entre-representaciones" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="tensiones-entre-representaciones"><span class="header-section-number">5.3.3</span> Tensiones entre representaciones</h3>
<p>El análisis revela que los youtubers no simplemente reproducen representaciones hegemónicas, sino que las negocian activamente. Identificamos tres tensiones centrales.</p>
<p><strong>Tensión global/local.</strong> El 60% de los videos muestran elementos de “glocalidad” <span class="citation" data-cites="robertson1995">(<a href="referencias.html#ref-robertson1995" role="doc-biblioref">Robertson, 1995</a>)</span>, combinando formatos globales con contenido marcadamente local. Lucas Castel en “ESPECIAL DE HALLOWEEN” (VID 1) adopta un formato de YouTube ampliamente global, pero explicita inmediatamente las condiciones locales: “en Argentina la gente mayor no tiene idea de lo que es Halloween. Seguramente vos vas y tocas ahora un timbre y te esperan con un arma” (0:22-0:28). Los youtubers no ocultan esta tensión: la tematizan, la hacen visible, la convierten en contenido. Esta glocalidad refleja lo que <span class="citation" data-cites="garciacanclini1989">García Canclini (<a href="referencias.html#ref-garciacanclini1989" role="doc-biblioref">1995</a>)</span> conceptualizó como “culturas híbridas”, donde lo global y lo local no se excluyen, sino que se entretejen.</p>
<p><strong>Tensión autenticidad/performance.</strong> Todos los youtubers del corpus reivindican explícitamente su autenticidad (“yo soy así”, “no tengo filtros”) mientras ejecutan performances editadas, guionizadas y ajustadas a las lógicas algorítmicas de la plataforma. Los youtubers gestionan esta tensión mediante la exhibición selectiva del <em>backstage</em>: muestran “lo que no debería verse” —el cuarto desordenado, el momento vulnerable, el error técnico— como estrategia de autentificación, pero incluso ese <em>backstage</em> está cuidadosamente curado. La paradoja no es un defecto, sino el principio de funcionamiento: la autenticidad digital no es algo que se tiene o no se tiene, sino algo que se construye, se performa, se negocia constantemente.</p>
<p><strong>Tensión individual/comunitario.</strong> Los youtubers construyen simultáneamente el yo único (“soy diferente”, “no soy como los demás”) y la pertenencia generacional (“los jóvenes somos así”, “nos pasa a todos”). Esta doble articulación es constante: en un mismo video el youtuber puede reivindicar su singularidad absoluta y apelar a experiencias compartidas generacionalmente. Los youtubers exitosos son quienes logran ser simultáneamente “únicos como todos” y “como todos, pero únicos”. Esta tensión refleja lo que <span class="citation" data-cites="martinbarbero1998">Martín-Barbero (<a href="referencias.html#ref-martinbarbero1998" role="doc-biblioref">1993</a>)</span> denominó la dialéctica entre “individualización” y “comunidad” característica de las mediaciones tecnológicas contemporáneas.</p>
<p>Las identidades juveniles en los videoblogs no operan desde la coherencia o la estabilidad, sino desde la negociación permanente. Los youtubers no resuelven las tensiones: las administran, las convierten en contenido, las espectacularizan. Y en ese proceso configuran identidades que son simultáneamente auténticas y performadas, locales y globales, individuales y comunitarias. Identidades que, parafraseando a <span class="citation" data-cites="bernete2007">Bernete (<a href="referencias.html#ref-bernete2007" role="doc-biblioref">2007</a>)</span>, habitan el “entre” como su territorio natural.</p>
</section>
</section>
<section id="subjetividades-juveniles-de-la-teoría-a-la-operacionalización" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="subjetividades-juveniles-de-la-teoría-a-la-operacionalización"><span class="header-section-number">5.4</span> Subjetividades juveniles: de la teoría a la operacionalización</h2>
<p>Algunos antecedentes significativos han trazado el camino para este análisis. <span class="citation" data-cites="campos2007">Campos Rodríguez (<a href="referencias.html#ref-campos2007" role="doc-biblioref">2007</a>)</span> señala que los videoblogs funcionan como vehículos privilegiados para la expresión individual, aunque advierte la necesidad de abordarlos desde la formación de subculturas dentro del sistema de valores hegemónico. <span class="citation" data-cites="chau2010">Chau (<a href="referencias.html#ref-chau2010" role="doc-biblioref">2010</a>)</span> demuestra en qué medida YouTube provee una plataforma sociotécnica apta para mantener una cultura participativa entre sus usuarios. <span class="citation" data-cites="julien2012">Burke et al. (<a href="referencias.html#ref-julien2012" role="doc-biblioref">2009</a>)</span> señala que los medios participativos han derribado las barreras tradicionales entre creadores y consumidores, facilitando el desarrollo de comunidades virtuales donde los creadores optan por “incluir” a su audiencia. Sin embargo, <span class="citation" data-cites="banuelos2009">Bañuelos (<a href="referencias.html#ref-banuelos2009" role="doc-biblioref">2009</a>)</span> advierte que “YouTube reproduce las principales cualidades de la sociedad del espectáculo, basado en la estrategia de la ‘autoproducción’ limitada por la lógica de mercado y el plan de negocios del sitio” (p.&nbsp;23), lo que implica que la agencia de los youtubers se despliega dentro de límites estructurales concretos.</p>
<p>Nuestra propuesta analítica recoge los rasgos de la identidad propuestos por <span class="citation" data-cites="giddens1991">Giddens (<a href="referencias.html#ref-giddens1991" role="doc-biblioref">1991</a>)</span> en un entrecruzamiento con las características del ciberdiscurso juvenil desarrolladas por <span class="citation" data-cites="palazzo2010a">Palazzo (<a href="referencias.html#ref-palazzo2010a" role="doc-biblioref">2010</a>)</span>. Las propiedades del proyecto narrativo del yo según Giddens —continuidad biográfica, reflexividad, gestión del cuerpo, relación con el otro— encuentran en el vlog formas idóneas de materialización. El proyecto narrativo se inicia desde el momento mismo en que se elige una tecnología considerada apta para enunciar el yo, y opera en presente continuo: interesa primordialmente quién se es hoy, con referencias menos sistemáticas al pasado biográfico o al futuro proyectado.</p>
<p>La Tabla 4 sistematiza esta articulación: cada rasgo identitario propuesto por Giddens se corresponde con características del ciberdiscurso juvenil y se materializa en estrategias discursivas observables en el corpus.</p>
<div id="fig-tabla-giddens" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tabla-giddens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imagenes/viz20_tabla_giddens.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tabla-giddens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.3: Tabla 4. Articulación entre los rasgos de la identidad reflexiva (Giddens, 1991), las características del ciberdiscurso juvenil (Palazzo, 2010) y los marcadores discursivos identificados en el corpus de videoblogs (2012-2016).
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📊 Código fuente de esta visualización
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Generado con <a href="scripts/viz_giddens_tabla.py"><code>viz_giddens_tabla.py</code></a> desde los datos del corpus.</p>
</div>
</div>
</div>
<section id="repertorio-de-subjetividades-disponibles" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="repertorio-de-subjetividades-disponibles"><span class="header-section-number">5.4.1</span> Repertorio de subjetividades disponibles</h3>
<p>Del análisis cualitativo del corpus emergen seis subjetividades principales que los youtubers activan, combinan y modulan a lo largo de sus narrativas. Estas subjetividades no constituyen posiciones fijas o esencias identitarias inmutables, sino modos situados de ser y estar en el mundo que se actualizan mediante estrategias discursivas y multimodales específicas. Un mismo youtuber puede transitar entre diferentes subjetividades según el video, la temática, la audiencia proyectada o el momento de su trayectoria como creador. Son, en definitiva, repertorios culturalmente disponibles que los jóvenes despliegan estratégicamente: las identidades se construyen en la reiteración de actos, gestos y performances que van sedimentando gradualmente una apariencia de sustancia.</p>
<section id="el-creador-autodidacta" class="level4" data-number="5.4.1.1">
<h4 data-number="5.4.1.1" class="anchored" data-anchor-id="el-creador-autodidacta"><span class="header-section-number">5.4.1.1</span> El creador autodidacta</h4>
<p>Esta subjetividad se construye alrededor de la figura del joven que ha desarrollado competencias técnicas y creativas de manera autónoma, al margen de instituciones educativas formales. El youtuber que la activa se presenta como alguien que aprendió solo mediante el ensayo y el error, comparte generosamente su conocimiento con la comunidad, y reivindica la autonomía y la creatividad personal frente a las instituciones tradicionales.</p>
<p>El análisis cuantitativo del corpus revela que 31 de los 80 videos (38.75%) presentan un posicionamiento claro del youtuber como “experto” que enseña algo a su audiencia; 18 videos (22.5%) adoptan explícitamente el formato tutorial; y 24 menciones textuales refieren de manera directa al proceso de aprendizaje autodidacta. En Lucas Castel, el análisis técnico de sus producciones iniciales muestra recursos audiovisuales primitivos —planos inestables, cortes directos básicos— que no se ocultan, sino que se reivindican como parte del proceso de aprendizaje. Esta “torpeza” técnica inicial cumple una función identitaria: certifica que el creador empezó de cero.</p>
</section>
<section id="el-rebelde-transgresor" class="level4" data-number="5.4.1.2">
<h4 data-number="5.4.1.2" class="anchored" data-anchor-id="el-rebelde-transgresor"><span class="header-section-number">5.4.1.2</span> El rebelde transgresor</h4>
<p>Esta subjetividad se articula en torno al joven que desafía normas adultas en ámbitos escolares, familiares y sociales. Recurre frecuentemente al humor provocativo y al lenguaje explícito como marcas de autenticidad, y reivindica la libertad personal como valor supremo de la juventud.</p>
<p>Los datos del corpus evidencian la presencia significativa de esta subjetividad: 34 de los 80 videos (42.5%) incluyen contenido abiertamente transgresor o provocador; 21 videos (26.25%) presentan referencias sexuales o a temas tabú de manera deliberadamente explícita; el uso de lenguaje soez o explícito aparece en 28 videos (35%); y se identifican 19 casos donde los youtubers mencionan conflictos con figuras de autoridad. El caso de Julián Serrano resulta ilustrativo: en “10 personajes típicos de la secundaria” caracteriza paródicamente al “rebelde típico” que no se ata los cordones porque “él es tan malo y tan rebelde que no sigue las reglas”. La parodia no distancia a Serrano de esta subjetividad —al contrario, demuestra un conocimiento interno profundo de ella.</p>
</section>
<section id="el-joven-de-barrio-cercano" class="level4" data-number="5.4.1.3">
<h4 data-number="5.4.1.3" class="anchored" data-anchor-id="el-joven-de-barrio-cercano"><span class="header-section-number">5.4.1.3</span> El joven de barrio cercano</h4>
<p>Esta subjetividad construye proximidad con la audiencia mediante la énfasis en el origen popular y la visibilización constante de la vida cotidiana “normal”. El youtuber se presenta como “uno más”, alguien que comparte experiencias, espacios y dificultades comunes con sus seguidores.</p>
<p>Es la subjetividad más frecuente del corpus: 52 de los 80 videos (65%) abordan temáticas de vida cotidiana; las marcas de oralidad aparecen en 67 videos (83.75%); las referencias a espacios domésticos y barriales en 45 videos (56.25%). Lucas Castel en VID 1 enuncia: “Hoy estamos en la calle, en vez de filmar en mi casa como hacíamos antes.” La construcción pronominal inclusiva (“estamos”), el contraste entre el “antes” doméstico y el “ahora” exterior, la referencia a “mi casa” como espacio habitual de grabación: todo contribuye a construir cercanía horizontal. Mica Suárez la despliega con matices propios: “Que feo que estoy. Recién llegué a mi casa, son las seis y media de la tarde. La mancha de su madre. ¿Sabes lo que es entrar a la computadora, abrir mi canal y ver esto?” La imperfección deliberada (“que feo que estoy”), el léxico coloquial (“la mancha de su madre”), el espacio doméstico: construyen autenticidad desde lo ordinario.</p>
</section>
<section id="el-humorista-performático" class="level4" data-number="5.4.1.4">
<h4 data-number="5.4.1.4" class="anchored" data-anchor-id="el-humorista-performático"><span class="header-section-number">5.4.1.4</span> El humorista performático</h4>
<p>Esta subjetividad coloca el humor como estrategia principal de construcción identitaria. El youtuber ejecuta performance teatral explícita, construye personajes y situaciones cómicas elaboradas, y establece el entretenimiento como valor central.</p>
<p>Los datos muestran que 38 de los 80 videos (47.5%) incluyen humor y parodia como recursos centrales; la performance y teatralidad explícita aparece en 44 videos (55%); el uso de personajes definidos se identifica en 26 videos (32.5%). Lucas Castel construye situaciones humorísticas elaboradas en VID 1 (sale disfrazado a asustar personas en la calle y hace preguntas falsas sobre Halloween a transeúntes). Elchuiuical construye prácticamente toda su identidad desde el humor absurdo y la performance exagerada: “EL PEOR RAPERO DE LA HISTORIA” (VID 62) es el ejemplo más extremo del corpus.</p>
</section>
<section id="el-joven-reflexivointelectual" class="level4" data-number="5.4.1.5">
<h4 data-number="5.4.1.5" class="anchored" data-anchor-id="el-joven-reflexivointelectual"><span class="header-section-number">5.4.1.5</span> El joven reflexivo/intelectual</h4>
<p>Esta subjetividad construye al youtuber como pensador crítico que aborda temas “profundos” o existenciales. Se posiciona como alguien capaz de cuestionar el sentido común, valorizando el conocimiento y la reflexión como formas de capital cultural juvenil.</p>
<p>Se identifican 31 videos (38.75%) con temáticas vinculadas a emociones, motivación y autoayuda; 22 videos (27.5%) con contenido explícitamente reflexivo o filosófico; 18 videos (22.5%) con algún tipo de crítica social explícita. Mariano Bondar ejemplifica esta subjetividad de manera paradigmática: sus videos abordan consistentemente temas existenciales, salud mental y reflexiones sobre experiencias vitales significativas. Julián Serrano también la activa ocasionalmente, pese al título autoirónico de “FILOSOFANDO (?)” que marca distancia respecto de la pretensión filosófica.</p>
</section>
<section id="el-vulnerablesensible" class="level4" data-number="5.4.1.6">
<h4 data-number="5.4.1.6" class="anchored" data-anchor-id="el-vulnerablesensible"><span class="header-section-number">5.4.1.6</span> El vulnerable/sensible</h4>
<p>Esta subjetividad invierte lógicas tradicionales de fortaleza y debilidad al construir la exhibición de fragilidad emocional como fortaleza identitaria. El youtuber comparte experiencias dolorosas, construye comunidad desde la vulnerabilidad compartida, y —en el caso de los youtubers varones— desafía mandatos de masculinidad hegemónica que proscriben la expresión emocional profunda.</p>
<p>Los datos muestran que 19 videos (23.75%) presentan al youtuber en estado emocional alterado o visiblemente afectado; las narrativas explícitas de vulnerabilidad o confesión aparecen en 24 videos (30%); y 21 videos (26.25%) incluyen referencias a problemas personales graves o familiares. Mariano Bondar constituye el caso más representativo: al mencionar diagnóstico psiquiátrico, describir síntomas concretos (no ir al colegio, no comer, querer estar solo) y posicionarse como alguien con “autoridad experiencial sobre el tema” aunque con humildad epistémica (“no sé si de cómo superarla”), construye una credibilidad que deriva precisamente de haber atravesado el dolor.</p>
</section>
</section>
<section id="articulación-subjetividades-representaciones" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="articulación-subjetividades-representaciones"><span class="header-section-number">5.4.2</span> Articulación subjetividades × representaciones</h3>
<p>Las seis subjetividades identificadas no operan de manera aislada, sino que se articulan productivamente con las representaciones sociales de juventud. La siguiente tabla visualiza estas articulaciones.</p>
<p><strong>Articulación subjetividades × representaciones</strong></p>
<div id="tbl-subj-repr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-subj-repr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;5.1: Articulación entre subjetividades y representaciones sociales de juventud en el corpus.
</figcaption>
<div aria-describedby="tbl-subj-repr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Subjetividad</strong></th>
<th style="text-align: center;"><strong>Residentes digitales creativos</strong></th>
<th style="text-align: center;"><strong>Libertad y experimentación</strong></th>
<th style="text-align: center;"><strong>Youtuber como trabajo</strong></th>
<th style="text-align: center;"><strong>Autenticidad</strong></th>
<th style="text-align: center;"><strong>Juventud vulnerable</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Auténtico vulnerable</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Baja</td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;"><strong>Alta</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Rebelde irónico</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Baja</td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Media</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Emprendedor digital</strong></td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Baja</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Nativo afectivo</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Baja</td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Media</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Cronista de lo cotidiano</strong></td>
<td style="text-align: center;">Baja</td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Baja</td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Media</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Performer carismático</strong></td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;"><strong>Alta</strong></td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Media</td>
<td style="text-align: center;">Baja</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El <strong>auténtico vulnerable</strong> (Mariano Bondar en sus videos confesionales) articula con máxima intensidad autenticidad y vulnerabilidad: solo un yo percibido como genuino puede mostrarse vulnerable sin que esa vulnerabilidad sea leída como performance. El <strong>rebelde irónico</strong> (Julián Serrano en “FILOSOFANDO”) articula primariamente la representación de libertad y experimentación, desplegándola mediante una retórica de la irreverencia que desafía las expectativas adultas —la ironía funciona como escudo: permite decir cosas transgresoras manteniendo distancia.</p>
<p>El <strong>emprendedor digital</strong> (Lionel Ferro y Lucas Castel en videos sobre viajes a YouTube o eventos) es el que más explícitamente tematiza la plataforma como espacio profesional. El <strong>nativo afectivo</strong> (presente en segmentos de Mica Suárez y Julián Serrano) prioriza autenticidad, pero la despliega desde la transparencia emocional cotidiana, no desde la confesión dramática.</p>
<p>El <strong>cronista de lo cotidiano</strong> (Gonzalo Fonseca, Lucas Castel en vlogs domésticos) convierte la falta de acontecimiento en acontecimiento narrable. El <strong>performer carismático</strong> (Elchuiuical, Gonzalo Goette) es auténtico precisamente por la transparencia sobre la performance: no oculta que está actuando, y su credibilidad reside en eso.</p>
<p>Esta matriz permite visualizar cómo las construcciones identitarias de los youtubers no son invenciones espontáneas, sino que emergen de articulaciones creativas de recursos simbólicos socialmente disponibles.</p>
</section>
</section>
<section id="sistema-de-índices-ponderados" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sistema-de-índices-ponderados"><span class="header-section-number">5.5</span> Sistema de índices ponderados</h2>
<section id="justificación-metodológica" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="justificación-metodológica"><span class="header-section-number">5.5.1</span> Justificación metodológica</h3>
<p>Enfrentamos aquí una pregunta metodológica que no admite respuestas fáciles: ¿cómo operacionalizar dimensiones tan complejas como la glocalidad, la cercanía parasocial, la modulación pasional, la extimidad o la autenticidad performativa de manera que permitan comparaciones sistemáticas sin traicionar la riqueza interpretativa acumulada?</p>
<p>Nuestra posición se sitúa deliberadamente en el espacio productivo de esta tensión. Los cinco índices ponderados que presentamos —Glocalidad (IGL), Cercanía Parasocial (ICP), Modulación Pasional (IMP), Extimidad (IEX) y Autenticidad Performativa (IAP)— no aspiran a “medir” las identidades juveniles como si fueran propiedades objetivas y estables. Son, más modestamente, herramientas heurísticas: dispositivos que nos permiten hacer preguntas comparativas, identificar tipologías empíricas, visualizar tendencias estructurales que después deben ser reinterpretadas cualitativamente. Como ha argumentado <span class="citation" data-cites="boudon1984">Boudon (<a href="referencias.html#ref-boudon1984" role="doc-biblioref">1993</a>)</span>, los modelos cuantitativos en ciencias sociales no aspiran a capturar “la realidad” sino a generar representaciones simplificadas que faciliten el pensamiento teórico y la comunicación científica. En este sentido, los índices funcionan más como mapas que como fotografías: sacrifican deliberadamente ciertos detalles para hacer visible la topografía general del terreno.</p>
</section>
<section id="índice-de-glocalidad-igl" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="índice-de-glocalidad-igl"><span class="header-section-number">5.5.2</span> Índice de Glocalidad (IGL)</h3>
<p>Cuando Lucas Castel abre uno de sus videos diciendo “che boludo, la concha de la lora, no sabés lo que me pasó ayer” mientras lleva puesta una remera de Los Simpsons con música electrónica de fondo, está performando en ese instante la tensión constitutiva de las identidades juveniles contemporáneas. Su acento es inconfundiblemente argentino, su léxico es profundamente rioplatense, su corporalidad gestual responde a códigos comunicativos locales. Y sin embargo, la serie que referencia es global, la música circula por redes transnacionales, los temas que trata lo conectan con comunidades juveniles que trascienden las fronteras de Argentina.</p>
<p>Esta simultaneidad de lo local y lo global es lo que <span class="citation" data-cites="robertson1995">Robertson (<a href="referencias.html#ref-robertson1995" role="doc-biblioref">1995</a>)</span> denominó “glocalización”. Nuestro Índice de Glocalidad operacionaliza esta dimensión midiendo el equilibrio entre elementos culturales que anclan al youtuber en coordenadas territoriales específicas versus elementos que lo proyectan hacia comunidades juveniles transnacionales. La escala va de -10 (máxima localización) a +10 (máxima globalización), con el 0 representando equilibrio. Las variables que suman hacia lo global (+) incluyen: glocalidad y referencias culturales mixtas (+1.5), vocabulario gamer/web (+1), léxico web general (+1), referencias a viajes y experiencias (+1), y exteriores de viajes (+1.5). Las variables que restan hacia lo local (-) incluyen: dialecto propio marcado (-2), lenguaje dialectal y léxico juvenil argentino (-1), referencia a jerga juvenil local (-1), cambio de variedad dialectal (-1), y espacios privados/domésticos argentinos (-0.5).</p>
</section>
<section id="índice-de-cercanía-parasocial-icp" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="índice-de-cercanía-parasocial-icp"><span class="header-section-number">5.5.3</span> Índice de Cercanía Parasocial (ICP)</h3>
<p>“Hola Iutub, ¿cómo están? ¿Cómo estuvo su semana? La mía fue una locura, no van a creer lo que me pasó…” Así comienza Mica Suárez uno de sus videos, desplegando en quince segundos una batería completa de estrategias de construcción de cercanía: el vocativo colectivo, las preguntas directas, la promesa de compartir experiencia personal, el tono cálido y familiar.</p>
<p>El concepto de “interacción parasocial” fue introducido por Horton y <span class="citation" data-cites="wohl1956">Horton &amp; Wohl (<a href="referencias.html#ref-wohl1956" role="doc-biblioref">1956</a>)</span> en un artículo seminal sobre las relaciones que las audiencias televisivas desarrollaban con personalidades mediáticas. Aunque la relación es objetivamente unidireccional (la audiencia ve al youtuber, pero el youtuber no ve a la audiencia), los espectadores desarrollan sentimientos de conocimiento íntimo y cercanía que se asemejan a relaciones interpersonales genuinas. Nuestro Índice de Cercanía Parasocial operacionaliza esta dimensión en una escala de 0 a 10. Las variables que suman incluyen: uso del pronombre “ustedes” (+1), uso del tuteo (+1), referencias a la comunidad (+1.5), menciones de YouTube como espacio compartido (+1), llamados a la acción (+1.5), mención de otras redes sociales (+1), y existencia de rasgos de <em>backstage</em> como nombres de pila, familiaridad y vida cotidiana (+0.5 cada uno).</p>
</section>
<section id="índice-de-modulación-pasional-imp" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="índice-de-modulación-pasional-imp"><span class="header-section-number">5.5.4</span> Índice de Modulación Pasional (IMP)</h3>
<p>Todo enunciado tiene un contenido proposicional, y una “coloración” afectiva que modula cómo debe interpretarse ese contenido. Esta “coloración” es lo que la semiótica de las pasiones <span class="citation" data-cites="greimas1994">(<a href="referencias.html#ref-greimas1994" role="doc-biblioref">Greimas &amp; Fontanille, 1993</a>)</span> denomina modulación pasional. En el videoblog, esta dimensión adquiere complejidad especial porque los youtubers no solo dicen cosas, sino que las performan corporalmente ante la cámara: las emociones se exhiben mediante recursos multimodales que incluyen expresión facial, tono de voz, gestualidad corporal, edición de video y música de fondo.</p>
<p>Nuestro IMP se construye en una escala de 0 a 10. Las variables que suman incluyen: expresividad facial marcada (+2), gestualidad con manos (+1), corporalidad destacada (+1), estado emocional alterado (+2), música de fondo (+0.5), audios enlatados (+0.5), y clips insertados (+0.5). Las variables que restan incluyen: silencio como recurso (-1) y ausencia de música y efectos.</p>
</section>
<section id="índice-de-extimidad-iex" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="índice-de-extimidad-iex"><span class="header-section-number">5.5.5</span> Índice de Extimidad (IEX)</h3>
<p>“Lo íntimo deviene éxtimo” escribió Lacan para describir cómo aquello que debería permanecer protegido de la mirada ajena sale a la luz y se exhibe públicamente. <span class="citation" data-cites="sibilia2008">Sibilia (<a href="referencias.html#ref-sibilia2008" role="doc-biblioref">2008</a>)</span> retomó y desarrolló este concepto para analizar las nuevas formas de construcción del yo en internet. En el videoblog, la extimidad adquiere una materialidad especialmente intensa: los youtubers performan corporalmente su intimidad, la muestran en sus espacios domésticos, la sonorizan con sus voces, risas y llantos.</p>
<p>Nuestro IEX se construye en una escala de 0 a 10. Las variables que suman incluyen: espacio privado (+1), dormitorio específicamente (+1.5), referencias a familia y vínculos afectivos (+1), temática de amor, pareja y sexualidad (+1.5), exhibición del cuerpo (+1), vida cotidiana (+0.5), y existencia de rasgos de <em>backstage</em> como sexualidad, exhibición corporal, descuidos y nombres de pila (+0.5 cada uno). Los espacios públicos restan del índice.</p>
</section>
<section id="índice-de-autenticidad-performativa-iap" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="índice-de-autenticidad-performativa-iap"><span class="header-section-number">5.5.6</span> Índice de Autenticidad Performativa (IAP)</h3>
<p>“Ser auténtico” es el mandato más extendido y paradójico de las culturas digitales contemporáneas. Los youtubers nos exhortan a “ser nosotros mismos” mientras ejecutan performances cuidadosamente elaboradas. Esta paradoja no es un defecto del sistema, sino su principio de funcionamiento. “Autenticidad performativa” intenta capturar esto: la autenticidad digital no es algo que se tiene o no se tiene, sino algo que se construye, se performa, se negocia constantemente.</p>
<p>El IAP se construye como un ratio entre marcadores de autenticidad y marcadores de performance. Los marcadores de autenticidad incluyen: sinceridad (+2), dialecto propio (+1), marcas de oralidad (+1), referencias a vida cotidiana (+1), espacio privado (+1), errores visibles conservados (+1), y referencias autobiográficas (+1). Los marcadores de performance incluyen: performance y teatralidad (+2), personajes definidos (+1), música dramática (+0.5), edición muy elaborada (+0.5). El índice final es: <em>IAP = (Autenticidad / (Autenticidad + Performance)) × 10</em>.</p>
</section>
<section id="resultados-generales-del-corpus" class="level3" data-number="5.5.7">
<h3 data-number="5.5.7" class="anchored" data-anchor-id="resultados-generales-del-corpus"><span class="header-section-number">5.5.7</span> Resultados generales del corpus</h3>
<p>La aplicación de los cinco índices a los 80 videos del corpus revela patrones estructurales que merecen ser destacados.</p>
<p>En el <strong>IGL</strong>, la mediana se sitúa en 0.00 con una media de -0.30, indicando que el corpus en su conjunto mantiene un equilibrio entre elementos locales y globales, con ligera tendencia hacia lo local. El rango va desde -5.20 hasta +6.40, evidenciando alta variabilidad estratégica. El standard de desviación de 2.53 confirma que los youtubers modulan activamente su posicionamiento glocalidad.</p>
<p>En el <strong>ICP</strong>, la mediana es 4.50 y la media 4.58, con rango entre 1.50 y 7.50. La distribución relativamente simétrica y concentrada en valores medios-altos confirma empíricamente la hipótesis teórica: la construcción de cercanía parasocial es estrategia central y transversal del videoblog juvenil exitoso.</p>
<p>En el <strong>IMP</strong>, la mediana es 2.80 y la media 3.19, con rango entre 0.00 y 8.05. La distribución muestra asimetría positiva: se concentra en valores bajos-medios, pero con cola larga hacia la intensidad alta, lo que sugiere que la hiperexpresividad es un recurso selectivo, no la norma.</p>
<p>En el <strong>IEX</strong>, la mediana es 4.40 y la media 4.48, con rango amplio entre 0.28 y 8.53. La distribución relativamente amplia y centrada en valores medios evidencia que la extimidad es estrategia presente, pero calibrada: no exposición indiscriminada, sino gestión estratégica de la intimidad digital.</p>
<p>En el <strong>IAP</strong>, la mediana es 7.69 y la media 7.62, con rango entre 5.71 y 10.00. Todos los videos del corpus se concentran en valores altos, lo que valida que la autenticidad es condición estructural del videoblog exitoso: ningún video analizado puede prescindir de marcadores de genuinidad.</p>
<div id="tbl-indices-youtuber" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-indices-youtuber-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;5.2: Índices ponderados promedio por youtuber. IGL puede ser negativo (orientación local). Fuente: Elaboración propia a partir de <code>MATRIZ_FINAL_RESTAURADA.csv</code>.
</figcaption>
<div aria-describedby="tbl-indices-youtuber-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Youtuber</th>
<th style="text-align: left;">IGL</th>
<th style="text-align: left;">ICP</th>
<th style="text-align: left;">IMP</th>
<th style="text-align: left;">IEX</th>
<th style="text-align: left;">IAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lucas Castel</td>
<td style="text-align: left;">-0.40</td>
<td style="text-align: left;">5.21</td>
<td style="text-align: left;">4.55</td>
<td style="text-align: left;">5.61</td>
<td style="text-align: left;">7.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Julián Serrano</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">5.78</td>
<td style="text-align: left;">3.18</td>
<td style="text-align: left;">5.42</td>
<td style="text-align: left;">7.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mica Suárez</td>
<td style="text-align: left;">-0.68</td>
<td style="text-align: left;">5.06</td>
<td style="text-align: left;">3.18</td>
<td style="text-align: left;">4.59</td>
<td style="text-align: left;">7.68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mariano Bondar</td>
<td style="text-align: left;">-0.96</td>
<td style="text-align: left;">3.75</td>
<td style="text-align: left;">2.52</td>
<td style="text-align: left;">3.77</td>
<td style="text-align: left;">7.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gonzalo Goette</td>
<td style="text-align: left;">-0.24</td>
<td style="text-align: left;">3.56</td>
<td style="text-align: left;">2.70</td>
<td style="text-align: left;">2.97</td>
<td style="text-align: left;">8.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lionel Ferro</td>
<td style="text-align: left;">0.52</td>
<td style="text-align: left;">4.12</td>
<td style="text-align: left;">3.46</td>
<td style="text-align: left;">4.21</td>
<td style="text-align: left;">8.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elchuiuical</td>
<td style="text-align: left;">0.08</td>
<td style="text-align: left;">4.42</td>
<td style="text-align: left;">2.84</td>
<td style="text-align: left;">4.73</td>
<td style="text-align: left;">7.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gonzalo Fonseca</td>
<td style="text-align: left;">-1.16</td>
<td style="text-align: left;">4.73</td>
<td style="text-align: left;">3.12</td>
<td style="text-align: left;">4.57</td>
<td style="text-align: left;">7.30</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El análisis de temas mediante LDA sobre las transcripciones corrobora y enriquece estos resultados. Los 8 temas detectados presentan distribuciones diferenciadas de IAP promedio que confirman la tipología de subgéneros del capítulo anterior: el tema 5 (palabras clave: <em>dinero, dale, billetera, tijera, papel</em>; asociado a desafíos y apuestas) presenta el IAP más alto del corpus (8.43), confirmando que la exposición al riesgo apela directamente a la demanda de autenticidad del vínculo parasocial. El tema 2 (<em>estamos, dale, celular, sheldon, día</em>; asociado al vlog cotidiano de Gonzalo Goette) y el tema 8 (<em>yao, verdad, hotel, miren, fue</em>; asociados a situaciones de confrontación o storytime) presentan IAP ≈ 7.73. El tema más bajo (Tema 7: <em>duele, parece, sea, ah, va</em>) obtiene IAP = 6.82, el único por debajo de la media del corpus, lo que confirma que los videos de contenido más suave o indirecto construyen percepción de autenticidad con menor intensidad. La convergencia entre el análisis cualitativo y el modelado computacional refuerza la solidez de los hallazgos.</p>
<div id="fig-tabla-indices" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tabla-indices-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imagenes/viz21_tabla_indices.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tabla-indices-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.4: Índices ponderados promedio por youtuber. Escala de color relativa por índice (azul=valor mínimo del corpus, rojo=valor máximo). IGL puede ser negativo (orientación predominantemente local).
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📊 Código fuente de esta visualización
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Esta figura fue generada con el script <a href="scripts/viz_all.py"><code>viz_all.py</code></a>. Los datos provienen de <code>MATRIZ_FINAL_RESTAURADA.csv</code> (corpus: 80 videoblogs).</p>
</div>
</div>
</div>
</section>
</section>
<section id="estrategias-multimodales-de-construcción-subjetiva" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="estrategias-multimodales-de-construcción-subjetiva"><span class="header-section-number">5.6</span> Estrategias multimodales de construcción subjetiva</h2>
<p>Las seis subjetividades identificadas y los índices que las operacionalizan no flotan en el vacío ni se construyen únicamente mediante el discurso verbal. Las identidades digitales en el videoblog se configuran multimodalmente, a través de la articulación compleja de recursos corporales, espaciales, sonoros y visuales. Como ha demostrado <span class="citation" data-cites="kress2009">Kress (<a href="referencias.html#ref-kress2009" role="doc-biblioref">2010</a>)</span>, cada modo semiótico aporta potencialidades expresivas específicas que no pueden ser reducidas a otros modos.</p>
<section id="el-cuerpo-como-texto-identitario" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="el-cuerpo-como-texto-identitario"><span class="header-section-number">5.6.1</span> El cuerpo como texto identitario</h3>
<p>El análisis cuantitativo del corpus revela que el 40% de los videos presentan corporalidad destacada como recurso expresivo central. El cuerpo del youtuber no es un soporte neutro, sino un texto en sí mismo que se lee, se interpreta, se valora, se desea o se rechaza.</p>
<p>La gestualidad, documentada meticulosamente en la matriz de análisis, constituye el primer nivel de significación corporal. Los gestos enfáticos con las manos, presentes en el 83.75% del corpus, no solo acompañan el habla, sino que la modulan e intensifican. La gestualidad facial —que nuestro análisis registra como “comunicación facial muy marcada” en múltiples videos— construye intensidades emocionales específicas: el youtuber que cuenta algo triste con expresión grave pide empatía; el que narra algo gracioso con la sonrisa contenida que finalmente estalla construye complicidad humorística. Se identifican 8 videos (10%) con exhibición corporal explícita en formato “sin remera”, y 12 videos (15%) con estrategias de “beboteo” o coquetería deliberada. La youtuber femenina del corpus, Mica Suárez, tiende a estrategias corporales más contenidas que resisten activamente la hipersexualización de su cuerpo —lo que también es, en sí mismo, un posicionamiento identitario.</p>
</section>
<section id="geografías-de-la-autenticidad" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="geografías-de-la-autenticidad"><span class="header-section-number">5.6.2</span> Geografías de la autenticidad</h3>
<p>El corpus revela que el 52.5% de los videos se graban predominantemente en espacios privados (dormitorio y sala familiar) y el 47.5% en espacios públicos o exteriores. El análisis cualitativo revela que no se trata de una “preferencia” sino de estrategias espaciales que producen efectos semióticos radicalmente diferentes.</p>
<p>El dormitorio opera como el marcador de intimidad por excelencia. Al grabar desde su cuarto, el youtuber invita simbólicamente a la audiencia a ingresar en su espacio más íntimo, construyendo una ilusión de proximidad: esto es extimidad materializada <span class="citation" data-cites="sibilia2008">(<a href="referencias.html#ref-sibilia2008" role="doc-biblioref">Sibilia, 2008</a>)</span>. Los espacios exteriores y públicos significan aventura, libertad, exploración. El 30% de los videos incluyen cambios de escenario dentro del mismo video, construyendo dinamismo y agencia. Lucas Castel narra explícitamente este movimiento en VID 1: “Hoy estamos en la calle, en vez de filmar en mi casa como hacíamos antes.” El contraste entre el “antes” doméstico y el “ahora” exterior narra una evolución, un crecimiento.</p>
</section>
<section id="la-música-de-las-emociones" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="la-música-de-las-emociones"><span class="header-section-number">5.6.3</span> La música de las emociones</h3>
<p>El análisis cuantitativo muestra que el 56.25% de los videos incluyen música de fondo, el 38.75% incorporan efectos sonoros preproducidos, y el 15% utilizan el silencio estratégico como recurso semiótico. La música no opera como “fondo” decorativo, sino que construye atmósferas emocionales específicas y guía la respuesta afectiva de la audiencia.</p>
<p>Cuando Lucas Castel acompaña un tutorial de edición con música electrónica energética, está construyendo entusiasmo: asocia el aprendizaje técnico con placer y vitalidad. Cuando Mariano Bondar narra experiencias de duelo con música melancólica de fondo, está intensificando el dramatismo sin decirlo explícitamente. Los efectos sonoros cómicos (risas enlatadas, sonidos de dibujos animados) marcan explícitamente el registro humorístico y señalizan cuándo la audiencia debe interpretar algo como broma: en contextos de audiencias masivas y heterogéneas donde el humor puede malinterpretarse, estos efectos funcionan como instrucciones de lectura. El recurso más sofisticado es el silencio estratégico: en los videos de Mariano Bondar, el silencio acompaña frecuentemente los momentos de máxima vulnerabilidad, produciendo efecto de gravedad que ningún otro recurso sonoro podría generar.</p>
</section>
<section id="combinaciones-y-modulaciones-subjetivas" class="level3" data-number="5.6.4">
<h3 data-number="5.6.4" class="anchored" data-anchor-id="combinaciones-y-modulaciones-subjetivas"><span class="header-section-number">5.6.4</span> Combinaciones y modulaciones subjetivas</h3>
<p>Los youtubers raramente encarnan una única subjetividad de manera exclusiva. Las construcciones identitarias efectivas en YouTube resultan de combinaciones estratégicas y modulaciones situacionales según contextos comunicativos específicos, temas abordados y objetivos de cada video.</p>
<p>La combinación más frecuente del corpus articula la subjetividad del joven cercano con la del humorista performático (35% de los videos con ambas marcas). Construye humor desde la identificación horizontal: el youtuber hace reír no desde una posición de superioridad, sino desde la complicidad con experiencias compartidas. La articulación entre el rebelde transgresor y el vulnerable sensible aparece en el 18% de los casos: el youtuber no es un rebelde unidimensional, sino alguien que transgrede desde la conciencia de su propia fragilidad —cuando Mariano Bondar cuenta su depresión y simultáneamente desafía normas de masculinidad hegemónica, ambas subjetividades se potencian. La combinación reflexivo/intelectual con autodidacta (22% de casos) construye una forma de autoridad intelectual alternativa que se legitima en la experiencia vivida, no en credenciales institucionales. La combinación aparentemente paradójica entre performático y auténtico (28% de casos) evidencia algo fundamental: la autenticidad en YouTube no es la ausencia de performance, sino la capacidad de construir performances percibidas como genuinas.</p>
</section>
</section>
<section id="análisis-multimodal-de-seis-videos-paradigmáticos" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="análisis-multimodal-de-seis-videos-paradigmáticos"><span class="header-section-number">5.7</span> Análisis multimodal de seis videos paradigmáticos</h2>
<p>El análisis de las estrategias multimodales adquiere densidad interpretativa cuando se examina su funcionamiento concreto en videos específicos. Los seis videos que presentamos ilustran diferentes configuraciones identitarias, articulando las dimensiones visual, sonora y verbal en diálogo con los índices cuantitativos y las subjetividades identificadas. La selección responde a criterios de representatividad: cada uno ilustra un perfil diferenciado.</p>
<section id="lucas-castel-50-cosas-sobre-mí-vid-5-la-intimidad-calibrada" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="lucas-castel-50-cosas-sobre-mí-vid-5-la-intimidad-calibrada"><span class="header-section-number">5.7.1</span> Lucas Castel, “50 COSAS SOBRE MÍ” (VID 5): la intimidad calibrada</h3>
<p>Duración: 321 segundos (5:21 min). Word count: 2.250 palabras. Formato: Tag autobiográfico. Índices promedio del youtuber: IGL -0.40 | ICP 5.21 | IMP 4.55 | IEX 5.61 | IAP 7.28.</p>
<p>El video se desarrolla íntegramente en la sala del hogar familiar, con un fondo que exhibe elementos domésticos reconocibles. Esta elección espacial opera en una zona intermedia entre lo público y lo privado: no es el dormitorio (espacio de máxima intimidad) pero tampoco un estudio profesional. El encuadre alterna entre primer plano y plano general, permitiendo tanto la conexión facial directa con la audiencia como la contextualización espacial que valida la domesticidad del entorno. La vestimenta —pantalón negro, remera gris, canguro rayado— comunica accesibilidad: “así me visto en mi casa, así soy normalmente.”</p>
<p>La apertura del video establece inmediatamente el contrato comunicativo: “¿Qué tal amigos y amigas, cómo están? El video de hoy es un poco diferente, es más personal, vendría a ser. Lo vinieron haciendo otros youtubers y consiste en contar 50 cosas sobre mí. Así me conocerán un poquito más y saben quién carajo soy, ¿no?” El saludo inclusivo (“amigos y amigas”), la metacomunicación sobre el formato, y la expresión “quién carajo soy” introducen el registro coloquial que caracterizará todo el video.</p>
<p>El contenido revelado oscila estratégicamente entre lo trivial y lo significativo. Por un lado: “Una de las cosas que más me gusta hacer es comer budín mientras me baño” (1:14-1:18), confesión deliberadamente absurda que construye autenticidad por la revelación de excentricidades menores. Por otro: “Tuve solamente una novia y estoy soltero hace rato. Y la verdad se vive muy bien así, papá” (1:20-1:26), donde el tema potencialmente sensible se desactiva inmediatamente con el comentario jocoso. Esta oscilación entre revelación e ironía es característica del estilo de Lucas: permite intimidad calibrada donde la audiencia siente que “conoce” al youtuber sin que este se exponga a riesgos emocionales significativos. El IEX elevado (5.61) se materializa no mediante confesiones dramáticas, sino mediante acumulación de detalles cotidianos que construyen familiaridad gradual.</p>
</section>
<section id="julián-serrano-draw-my-life-vid-13-la-biografía-espectacularizada" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="julián-serrano-draw-my-life-vid-13-la-biografía-espectacularizada"><span class="header-section-number">5.7.2</span> Julián Serrano, “Draw My Life” (VID 13): la biografía espectacularizada</h3>
<p>Duración: 343 segundos (5:43 min). Word count: 1.235 palabras. Formato: Draw My Life (narrativa autobiográfica ilustrada). Índices promedio: IGL 0.44 | ICP 5.78 | IMP 3.18 | IEX 5.42 | IAP 7.51.</p>
<p>El formato Draw My Life impone restricciones visuales específicas: la imagen principal es una pizarra donde una mano dibuja mientras la voz narra. El cuerpo del youtuber está ausente durante la mayor parte del video, sustituido por dibujos esquemáticos. Esta ausencia corporal es significativa precisamente porque Julián es el youtuber del corpus que más capitaliza su corporalidad como recurso identitario: en el Draw My Life, esa corporalidad se sublima. No vemos su cuerpo, pero escuchamos su voz narrando su historia.</p>
<p>El video despliega una narrativa biográfica completa desde el nacimiento hasta el presente, articulando humor irreverente con momentos de emoción genuina. La estrategia narrativa predominante combina humor con deflexión de lo dramático: “Hasta que un día, chan chan chan, se rompió el condón y nací yo. Dándole fin a la joda de mi viejo y fin al estudio y proyectos de vida de mamá” (0:54-1:03). La revelación de un embarazo no planificado se enmarca mediante onomatopeya dramática irónica y se neutraliza con el humor. Pero el video incluye también momentos de emoción no deflectada: “Yolanda se llama haciendo honor a mi abuela, la mamá de Oscar. Se mudó al cielo cuando tenía apenas 7 años. Te queremos, Saúl” (1:12-1:19). La mención de la abuela fallecida introduce una pausa emocional genuina que contrasta con el tono predominante y demuestra capacidad de modular entre humor y emoción.</p>
<p>El Draw My Life de Julián ejemplifica la “narrativa identitaria espectacularizada”: una biografía completa contada mediante estrategias que la hacen entretenida, compartible, memorable. El formato global (Draw My Life es un género transnacional de YouTube) se ejecuta con marcada localización: el acento, los nombres de lugares argentinos, las referencias culturales específicas. Su IGL positivo (0.44) es el más alto del corpus en valores positivos, y se materializa precisamente en esta combinación.</p>
</section>
<section id="mariano-bondar-como-superé-la-muerte-de-mi-amigo-vid-50-el-límite-de-la-extimidad" class="level3" data-number="5.7.3">
<h3 data-number="5.7.3" class="anchored" data-anchor-id="mariano-bondar-como-superé-la-muerte-de-mi-amigo-vid-50-el-límite-de-la-extimidad"><span class="header-section-number">5.7.3</span> Mariano Bondar, “COMO SUPERÉ LA MUERTE DE MI AMIGO” (VID 50): el límite de la extimidad</h3>
<p>Duración: 1.113 segundos (18:33 min). Word count: 2.570 palabras. Formato: Video confesional/reflexivo. Índices promedio: IGL -0.96 | ICP 3.75 | IMP 2.52 | IEX 3.77 | IAP 7.27.</p>
<p>El video se desarrolla en la sala del hogar, con Mariano en primer plano sostenido durante toda la duración. El fondo es neutro y despojado, centrando la atención exclusivamente en el rostro. Esta economía visual es significativa: no hay entretenimiento visual que compita con el contenido verbal, no hay cortes a imágenes ilustrativas, no hay efectos visuales. El plano fijo sostenido durante 18 minutos es una decisión estética radical en el contexto del videoblog, donde los cortes dinámicos son norma. Esta quietud produce efecto de gravedad: el video demanda atención sostenida porque su estructura visual no ofrece estímulos alternativos.</p>
<p>La música de fondo puede parecer contradictoria con el tono confesional, pero opera como colchón emocional que sostiene al espectador durante un relato extenso y emocionalmente demandante. La ausencia de efectos sonoros humorísticos es total y deliberada: no hay alivio cómico, no hay escape del peso emocional.</p>
<p>El núcleo del video articula la experiencia de pérdida con sus consecuencias psicológicas de manera que excede lo habitual en el género. La frase “no lo he hablado con nadie realmente” posiciona al video como espacio de intimidad más profunda que las relaciones cara a cara: el youtuber puede decirle a millones de espectadores lo que no pudo decir a amigos o familiares. Y el cierre del video explicita esta lógica con una lucidez notable:</p>
<blockquote class="blockquote">
<p>“Al menos mi historia es real, y sabés que acá no hay nada que te haya dibujado. Es un alivio poder contarles esto. Como siempre, gracias por el espacio.” (VID 50, 17:15-17:33)</p>
</blockquote>
<p>“Gracias por el espacio” transforma a la audiencia de espectadores en testigos, y al canal de plataforma en espacio terapéutico. La insistencia en que “mi historia es real” no es un gesto de autenticidad performativa, sino una declaración de pacto: Bondar le está pidiendo a su público que lo crea, y la intensidad del pedido es proporcional a la gravedad de lo confesado.</p>
<p>Este video representa un caso límite que ilumina, por contraste, el funcionamiento habitual de la extimidad en el corpus. El IEX promedio de Mariano (3.77), uno de los más bajos, indica que este nivel de exposición es excepcional: la extimidad de Bondar opera por picos dramáticos más que por exhibición constante, y eso es lo que hace que los momentos de apertura radical adquieran peso extraordinario.</p>
</section>
<section id="mica-suárez-50-cosas-sobre-mí-vid-74-la-autenticidad-femenina" class="level3" data-number="5.7.4">
<h3 data-number="5.7.4" class="anchored" data-anchor-id="mica-suárez-50-cosas-sobre-mí-vid-74-la-autenticidad-femenina"><span class="header-section-number">5.7.4</span> Mica Suárez, “50 COSAS SOBRE MÍ” (VID 74): la autenticidad femenina</h3>
<p>Duración: 988 segundos (16:28 min). Word count: 2.849 palabras. Formato: Tag autobiográfico. Índices promedio: IGL -0.68 | ICP 5.06 | IMP 3.18 | IEX 4.59 | IAP 7.68.</p>
<p>A diferencia de otros videos del formato, Mica alterna entre múltiples espacios: dormitorio, sala y exteriores. Esta movilidad espacial construye dinamismo visual y exhibe diferentes facetas de su vida cotidiana. El fondo del dormitorio —con posters de regalos de fans— evidencia la relación bidireccional con la audiencia: la decoración misma es un producto de esa relación.</p>
<p>La apertura establece autoconciencia sobre el formato y posicionamiento dentro de la comunidad: “Hola Youtube, como habrán visto en el título del video, hoy voy a hacer un tag. Ya sé que el 50 cosas sobre mí ya lo hicieron todos los youtubers. De hecho creo que 9 de cada 10 youtubers lo hicieron. Pero nada, yo lo quería hacer porque no me quería dejar con las ganas. Creo que soy la única pelotuda que no lo hizo” (0:03-0:19). La autodescripción como “la única pelotuda” combina autocrítica humorística con reivindicación de agencia: hace el video porque quiere, no porque la tendencia la presione.</p>
<p>El video de Mica ilustra una construcción de autenticidad específicamente generizada. Su IEX de 4.59 indica exposición moderada, sin recurrir ni a la contención extrema ni a la confesión dramática. La subjetividad desplegada combina el “joven de barrio cercano” con el “vulnerable/sensible”, modulada por la experiencia femenina: la vulnerabilidad se expresa en términos de bullying y presiones estéticas más que en crisis existenciales.</p>
</section>
<section id="gonzalo-goette-besando-mujeres-frente-a-sus-novios-vid-52-la-autenticidad-por-riesgo" class="level3" data-number="5.7.5">
<h3 data-number="5.7.5" class="anchored" data-anchor-id="gonzalo-goette-besando-mujeres-frente-a-sus-novios-vid-52-la-autenticidad-por-riesgo"><span class="header-section-number">5.7.5</span> Gonzalo Goette, “BESANDO MUJERES FRENTE A SUS NOVIOS” (VID 52): la autenticidad por riesgo</h3>
<p>Duración: 218 segundos (3:38 min). Word count: 424 palabras. Formato: Prank / Experimento social. Índices promedio: IGL -0.24 | ICP 3.56 | IMP 2.70 | IEX 2.97 | IAP 8.04.</p>
<p>El video se desarrolla íntegramente en exteriores urbanos. La cámara opera en plano general priorizando la documentación de la situación sobre la intimidad del primer plano. El contenido verbal es mínimo y funcional: “Hola gente, hoy voy a ir a besar chicas a la calle usando un truco, pero lo voy a hacer enfrente de sus novios. Vamos a ver qué pasa” (0:00-0:05). Este contrato establece transgresión social, riesgo e incertidumbre. El atractivo del video reside precisamente en que las reacciones son impredecibles.</p>
<p>El video de Goette representa una vía alternativa de construcción de autenticidad que no depende de la confesión íntima ni de la exhibición del espacio privado. Su IAP, el más alto del corpus (8.04), se construye paradójicamente mediante la exposición al riesgo real: los golpes, insultos o rechazos que puede recibir no pueden ser guionados. La “verdad” del video reside en que Gonzalo efectivamente se expone a consecuencias impredecibles. Esto explica la aparente contradicción de tener el IAP más alto junto con el IEX más bajo: Gonzalo es auténtico no porque muestre su interioridad, sino porque pone su cuerpo en situaciones de fricción social real. No narra su yo; lo pone a prueba en el encuentro con el otro.</p>
</section>
<section id="lionel-ferro-les-presento-al-amor-de-mi-vida-vid-33-la-autenticidad-profesionalizada" class="level3" data-number="5.7.6">
<h3 data-number="5.7.6" class="anchored" data-anchor-id="lionel-ferro-les-presento-al-amor-de-mi-vida-vid-33-la-autenticidad-profesionalizada"><span class="header-section-number">5.7.6</span> Lionel Ferro, “LES PRESENTO AL AMOR DE MI VIDA” (VID 33): la autenticidad profesionalizada</h3>
<p>Duración: 681 segundos (11:21 min). Word count: 1.634 palabras. Formato: Vlog con invitado (hermano menor). Índices promedio: IGL 0.52 | ICP 4.12 | IMP 3.46 | IEX 4.21 | IAP 8.23.</p>
<p>El video se desarrolla en espacios domésticos, pero con características que lo distinguen de otros youtubers. La matriz registra “entornos domésticos sin edición aparente”, pero el análisis cualitativo revela mayor control técnico: iluminación más uniforme, encuadre más estable, composición más cuidada. La vestimenta de Lionel (ropa deportiva, cadena de coco) connota un estilo juvenil globalizado más que un arraigo local específico, coherente con el IGL más alto del corpus (0.52).</p>
<p>La apertura exhibe autoconciencia sobre la imagen pública: “Yo creo que ahí estamos bien, ¿no? Estoy fachero ahí para empezar mi nuevo video, ¿o no? ¿Sí o no? Estoy fachero para empezar mi nuevo video” (0:00-0:08). La repetición de “fachero” y la verificación con alguien fuera de cámara evidencian preocupación explícita por la apariencia. Esta transparencia sobre la construcción de imagen funciona paradójicamente como marcador de autenticidad: Lionel no pretende que su atractivo es natural o despreocupado; admite que lo trabaja.</p>
<p>El video de Lionel ilustra una forma de autenticidad que no depende de la espontaneidad amateur, sino de la transparencia sobre la profesionalización. Su IAP elevado (8.23), segundo más alto del corpus, se construye mediante la admisión explícita de que hay trabajo detrás de la imagen: no simular que no hay producción, sino integrar la producción como parte de la identidad.</p>
</section>
<section id="síntesis-comparativa" class="level3" data-number="5.7.7">
<h3 data-number="5.7.7" class="anchored" data-anchor-id="síntesis-comparativa"><span class="header-section-number">5.7.7</span> Síntesis comparativa</h3>
<p>El análisis de estos seis videos revela que las estrategias multimodales no operan de manera uniforme, sino que se configuran en combinaciones específicas que producen efectos identitarios diferenciados. Lucas Castel despliega intimidad calibrada mediante espacio doméstico intermedio, contención gestual y regulación humorística. Julián Serrano construye la biografía espectacularizada mediante la sublimación del cuerpo en el formato Draw My Life. Mariano Bondar alcanza la confesión radical mediante espacio despojado, plano fijo y música discreta sin efectos. Mica Suárez articula autenticidad femenina mediante movilidad espacial y gestualidad expresiva. Gonzalo Goette produce autenticidad por riesgo mediante espacio público exclusivo y audio ambiental no controlado. Lionel Ferro construye autenticidad profesionalizada mediante control técnico visible y transparencia sobre la producción.</p>
<p>La constante estructural que atraviesa todos los casos es la necesidad de alguna forma de autenticidad percibida: ningún video analizado presenta una configuración donde la performance pura desplace completamente los marcadores de genuinidad. Pero las vías para construir esa autenticidad son múltiples: puede residir en la intimidad compartida, en la vulnerabilidad expuesta, en el riesgo asumido, en la transparencia sobre la producción, o en la acumulación de detalles cotidianos.</p>
</section>
</section>
<section id="perfiles-identitarios-por-youtuber" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="perfiles-identitarios-por-youtuber"><span class="header-section-number">5.8</span> Perfiles identitarios por youtuber</h2>
<p>El análisis de los índices promedio por youtuber permite identificar perfiles que complementan el análisis video por video.</p>
<p><strong>Lucas Castel</strong> (IMP 4.55, máximo del corpus) es el “youtuber expresivo”: capitaliza la energía, el humor físico, la gestualidad amplia y la variación emocional constante. Su IGL ≈ 0 refleja equilibrio casi perfecto entre elementos locales y globales. El IEX elevado (5.61) indica disposición a la exhibición íntima modulada por la ironía.</p>
<p><strong>Julián Serrano</strong> (ICP 5.78, máximo del corpus) es el “youtuber seductor”: capitaliza el vínculo afectivo con su audiencia, particularmente femenina, mediante estrategias de cercanía, exhibición corporal calibrada y construcción de deseabilidad. IEX también elevado (5.42), coherente con una presencia más íntima.</p>
<p><strong>Mica Suárez</strong> presenta un perfil notablemente equilibrado, sin valores extremos en ningún índice. El IAP elevado (7.68) sugiere fuerte percepción de autenticidad con menor componente performático visible. Es la “youtuber reflexiva equilibrada”: construye autenticidad mediante combinación balanceada de estrategias.</p>
<p><strong>Mariano Bondar</strong> (IGL -0.96, fuerte anclaje local) presenta valores relativamente bajos en IMP (2.52) e IEX (3.77), lo que podría parecer contradictorio con su imagen de youtuber “confesional”. Sin embargo, estos promedios reflejan que la mayoría de sus videos mantienen un registro contenido, lo que hace que sus momentos de apertura radical adquieran peso extraordinario precisamente por contraste. Es el “youtuber auténtico por contraste”.</p>
<p><strong>Gonzalo Goette</strong> (IAP 8.04, máximo del corpus; IEX 2.97, mínimo del corpus) es el “bromista (<em>prankster</em>) auténtico”: credibilidad construida no mediante revelación íntima, sino mediante exposición a riesgo real. Su ICP relativamente bajo (3.56) refleja que no apuesta a la cercanía parasocial tradicional.</p>
<p><strong>Lionel Ferro</strong> (IGL 0.52, máximo del corpus; ICP 3.83, mínimo del corpus) es el “youtuber profesionalizado”: construye autenticidad no simulando amateurismo, sino siendo transparente sobre su condición de creador profesional de contenidos. El IGL más alto del corpus, coherente con aspiraciones y conexiones que trascienden el ámbito local.</p>
<p><strong>Elchuiuical</strong> (IAP 7.66, IEX 4.73) representa el “caos performático”: el humor absurdo y la performance exagerada son centrales, con valores medios en la mayoría de los índices. Su equilibrio en IGL (0.08 ≈ 0) refleja que opera en un espacio ni claramente local ni claramente global.</p>
<p><strong>Gonzalo Fonseca</strong> (IGL -1.16, mínimo del corpus) es el polo de máxima localización. Construye identidad desde el arraigo territorial y la comunidad barrial más que desde la proyección global. Su IAP (7.30) es competitivo pese a la menor espectacularización de la producción.</p>
</section>
<section id="conclusiones-parciales" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="conclusiones-parciales"><span class="header-section-number">5.9</span> Conclusiones parciales</h2>
<section id="hallazgos-estructurales" class="level3" data-number="5.9.1">
<h3 data-number="5.9.1" class="anchored" data-anchor-id="hallazgos-estructurales"><span class="header-section-number">5.9.1</span> Hallazgos estructurales</h3>
<p>El análisis de los 80 videos que conforman el corpus permite identificar patrones que configuran lo que podríamos llamar la “gramática” de las identidades digitales juveniles en el videoblog argentino del período 2012-2016.</p>
<p>La <strong>autenticidad emerge como condición estructural del género</strong>. El IAP promedio del corpus (7.62) con concentración en valores altos (ningún video por debajo de 5.71) demuestra que todos los youtubers exitosos mantienen marcadores de autenticidad suficientes para evitar ser percibidos como artificiales. Sin embargo, las vías para construir esa autenticidad son múltiples: intimidad compartida, vulnerabilidad expuesta, riesgo asumido, transparencia sobre la producción, o acumulación de detalles cotidianos. Esto implica que la demanda de autenticidad es estructural, pero su respuesta es estilísticamente diversa.</p>
<p>La <strong>cercanía parasocial se confirma como estrategia central</strong>. El ICP promedio de 4.58 con distribución concentrada en valores medios-altos indica que la construcción de ilusión de relación cercana con la audiencia no es opcional, sino constitutiva del género. Incluso los videos más “distantes” del corpus mantienen elementos mínimos de construcción de cercanía —el ICP nunca cae por debajo de 1.50.</p>
<p>La <strong>glocalidad se revela como dimensión negociable</strong>. La distribución del IGL cerca del cero con alta variabilidad (SD: 2.53, rango: -5.20/+6.40) indica que los youtubers modulan estratégicamente su posicionamiento entre lo local y lo global según contexto. El corpus en su conjunto gravita ligeramente hacia lo local (-0.30), pero hay casos en ambos polos que coexisten sin contradicción: ser profundamente local (Gonzalo Fonseca) o globalmente orientado (Lionel Ferro) son estrategias igualmente viables para construir identidad juvenil exitosa en YouTube.</p>
<p>La <strong>extimidad opera como recurso calibrado</strong>. La variabilidad del IEX (rango: 0.28 a 8.53) demuestra que los youtubers gestionan estratégicamente su intimidad digital, alternando entre videos más reservados y videos intensamente íntimos. No hay correlación necesaria entre IEX alto e IAP alto, lo que evidencia que la autenticidad no requiere necesariamente alta exposición íntima.</p>
</section>
<section id="articulación-entre-lo-teórico-y-lo-empírico" class="level3" data-number="5.9.2">
<h3 data-number="5.9.2" class="anchored" data-anchor-id="articulación-entre-lo-teórico-y-lo-empírico"><span class="header-section-number">5.9.2</span> Articulación entre lo teórico y lo empírico</h3>
<p>Los hallazgos empíricos del corpus permiten revisitar y enriquecer los marcos teóricos de partida. La noción de “culturas híbridas” de <span class="citation" data-cites="garciacanclini1989">García Canclini (<a href="referencias.html#ref-garciacanclini1989" role="doc-biblioref">1995</a>)</span> se confirma plenamente: las identidades juveniles del corpus articulan lo local y lo global en configuraciones complejas que no resuelven la tensión, sino que la administran. Los “entre” de <span class="citation" data-cites="bernete2007">Bernete (<a href="referencias.html#ref-bernete2007" role="doc-biblioref">2007</a>)</span> se materializan discursivamente como tensiones productivas.</p>
<p>La noción de extimidad de <span class="citation" data-cites="sibilia2008">Sibilia (<a href="referencias.html#ref-sibilia2008" role="doc-biblioref">2008</a>)</span> adquiere matices importantes a la luz del corpus: no se trata de una exhibición indiscriminada, sino de una gestión estratégica que alterna entre revelación y reserva. Los youtubers con IEX promedio bajo pueden producir momentos de máxima extimidad precisamente porque su contención habitual les otorga credibilidad —la rareza del momento intenso es parte de su efecto.</p>
<p>El concepto de interacción parasocial de Horton y <span class="citation" data-cites="wohl1956">Horton &amp; Wohl (<a href="referencias.html#ref-wohl1956" role="doc-biblioref">1956</a>)</span> se confirma como herramienta analítica vigente, aunque con especificidades del medio digital: la interactividad de los comentarios, las métricas visibles de engagement y la posibilidad de respuesta directa introducen elementos que complejizan la unidireccionalidad original del concepto.</p>
</section>
<section id="identidades-como-montajes-afectivos-multimodales" class="level3" data-number="5.9.3">
<h3 data-number="5.9.3" class="anchored" data-anchor-id="identidades-como-montajes-afectivos-multimodales"><span class="header-section-number">5.9.3</span> Identidades como montajes afectivos multimodales</h3>
<p>El análisis multimodal revela que las identidades digitales juveniles no se construyen únicamente mediante el discurso verbal, sino mediante la articulación compleja de recursos corporales, espaciales, sonoros y visuales. El cuerpo significa mediante gestualidad, exhibición y vestimenta; el espacio comunica intimidad, autenticidad y movilidad; el sonido modula intensidades emocionales, marca registros, construye atmósferas. Esta multimodalidad no es decorativa, sino constitutiva: las mismas palabras pronunciadas en diferentes espacios, con diferentes músicas de fondo, con diferentes gestualidades corporales, producen efectos identitarios radicalmente distintos. Las identidades juveniles en YouTube son montajes, en el sentido cinematográfico del término: construcciones que emergen de la articulación de elementos heterogéneos cuyo sentido no reside en cada componente aislado, sino en su combinación específica.</p>
</section>
<section id="condiciones-de-posibilidad-y-límites-estructurales" class="level3" data-number="5.9.4">
<h3 data-number="5.9.4" class="anchored" data-anchor-id="condiciones-de-posibilidad-y-límites-estructurales"><span class="header-section-number">5.9.4</span> Condiciones de posibilidad y límites estructurales</h3>
<p>Las identidades juveniles en el videoblog no son creaciones de la nada, sino articulaciones de recursos simbólicos socialmente disponibles. Las representaciones de juventud analizadas funcionan como condiciones de posibilidad que delimitan qué es narrable y cómo. Las subjetividades identificadas constituyen repertorios culturalmente disponibles, no invenciones individuales. Sin embargo, esta determinación estructural no anula la agencia de los youtubers: dentro de los límites del campo, existen múltiples posiciones posibles —profesionalizados o amateurs, globales o locales, confesionales o reservados, humorísticos o reflexivos. Los youtubers exitosos son aquellos que logran encontrar posiciones distintivas dentro del espacio de posibilidades, diferenciándose de competidores mientras mantienen los elementos mínimos que el género exige.</p>
<p>Este capítulo ha analizado las identidades juveniles en el videoblog desde una perspectiva predominantemente estructural: representaciones disponibles, subjetividades como repertorios, índices como patrones. Sin embargo, las identidades no son solo estructuras, sino también procesos que se despliegan en el tiempo. El capítulo siguiente abordará esta dimensión temporal mediante el análisis de trayectorias: cómo evolucionan los canales, cómo se transforman las estrategias identitarias, y cómo los youtubers negocian con las demandas cambiantes de audiencias y algoritmos. Las identidades digitales juveniles que hemos analizado no son esencias fijas, sino construcciones en movimiento, negociaciones permanentes entre lo que el youtuber quiere ser, lo que su audiencia espera, lo que la plataforma permite y premia, y lo que los recursos simbólicos disponibles habilitan. Son, en definitiva, proyectos reflexivos del yo <span class="citation" data-cites="giddens1991">(<a href="referencias.html#ref-giddens1991" role="doc-biblioref">Giddens, 1991</a>)</span> mediados tecnológicamente, situados culturalmente, y sostenidos comunitariamente.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-banuelos2009" class="csl-entry" role="listitem">
Bañuelos, J. (2009). YouTube como plataforma de la sociedad del espect<span>á</span>culo. <em>Razón y Palabra</em>, <em>14</em>(66).
</div>
<div id="ref-bernete2007" class="csl-entry" role="listitem">
Bernete, F. (2007). Identidades y mediadores de la comunicaci<span>ó</span>n entre j<span>ó</span>venes. <em>Revista de Estudios de Juventud</em>.
</div>
<div id="ref-boudon1984" class="csl-entry" role="listitem">
Boudon, R. (1993). <em>El lugar del desorden: Cr<span>í</span>tica de las teor<span>í</span>as del cambio social</em>. Gedisa.
</div>
<div id="ref-julien2012" class="csl-entry" role="listitem">
Burke, S. C., Snyder, S., &amp; Rager, R. C. (2009). An assessment of faculty usage of <span>YouTube</span> as a teaching resource. <em>The Internet Journal of Allied Health Sciences and Practice</em>, <em>7</em>(1), 1–8. <a href="https://doi.org/10.46743/1540-580X/2009.1227">https://doi.org/10.46743/1540-580X/2009.1227</a>
</div>
<div id="ref-campos2007" class="csl-entry" role="listitem">
Campos Rodríguez, P. (2007). El discurso multimodal en YouTube. <em>Revista Latinoamericana de Estudios Del Discurso</em>, <em>7</em>(1), 71–92.
</div>
<div id="ref-chau2010" class="csl-entry" role="listitem">
Chau, C. (2010). YouTube as a participatory culture. <em>New Directions for Youth Development</em>, <em>2010</em>(128), 65–74. <a href="https://doi.org/10.1002/yd.376">https://doi.org/10.1002/yd.376</a>
</div>
<div id="ref-vandijck2018" class="csl-entry" role="listitem">
Dijck, J. van, Poell, T., &amp; Waal, M. de. (2018). <em>The platform society: Public values in a connective world</em>. Oxford University Press.
</div>
<div id="ref-feixa2014" class="csl-entry" role="listitem">
Feixa, C. (2014). <em>De la generaci<span>ó</span>n@ a la #generaci<span>ó</span>n. La juventud en la era digital</em>. NED Ediciones / Gedisa.
</div>
<div id="ref-feixa1998" class="csl-entry" role="listitem">
Feixa P‘ampols, C. (1998). <em>De j<span>ó</span>venes, bandas y tribus: Antropolog<span>ı́</span>a de la juventud</em>. Ariel.
</div>
<div id="ref-garciacanclini1989" class="csl-entry" role="listitem">
García Canclini, N. (1995). <em>Hybrid cultures: Strategies for entering and leaving modernity</em>. University of Minnesota Press.
</div>
<div id="ref-giddens1991" class="csl-entry" role="listitem">
Giddens, A. (1991). <em>Modernity and self-identity: Self and society in the late modern age</em>. Polity Press.
</div>
<div id="ref-goffman1959" class="csl-entry" role="listitem">
Goffman, E. (1959). <em>The presentation of self in everyday life</em>. Anchor Books.
</div>
<div id="ref-greimas1994" class="csl-entry" role="listitem">
Greimas, A. J., &amp; Fontanille, J. (1993). <em>The semiotics of passions: From states of affairs to states of feelings</em>. University of Minnesota Press.
</div>
<div id="ref-wohl1956" class="csl-entry" role="listitem">
Horton, D., &amp; Wohl, R. R. (1956). Mass communication and para-social interaction: Observations on intimacy at a distance. <em>Psychiatry</em>, <em>19</em>(3), 215–229. <a href="https://doi.org/10.1080/00332747.1956.11023049">https://doi.org/10.1080/00332747.1956.11023049</a>
</div>
<div id="ref-jodelet1986" class="csl-entry" role="listitem">
Jodelet, D. (1984). La representaci<span>ó</span>n social: Fen<span>ó</span>meno, concepto y teor<span>í</span>a. In S. Moscovici (Ed.), <em>Psicolog<span>í</span>a social II</em>. Paid<span>ó</span>s.
</div>
<div id="ref-kress2009" class="csl-entry" role="listitem">
Kress, G. (2010). <em>Multimodality: A social semiotic approach to contemporary communication</em>. Routledge.
</div>
<div id="ref-labov1972" class="csl-entry" role="listitem">
Labov, W. (1972). <em>Sociolinguistic patterns</em>. University of Pennsylvania Press.
</div>
<div id="ref-martinbarbero1998" class="csl-entry" role="listitem">
Martín-Barbero, J. (1993). <em>Communication, culture and hegemony: From the media to mediations</em>. SAGE Publications.
</div>
<div id="ref-marwick2013" class="csl-entry" role="listitem">
Marwick, A. E. (2013). <em>Status update: Celebrity, publicity, and branding in the social media age</em>. Yale University Press.
</div>
<div id="ref-montecinosoto2005" class="csl-entry" role="listitem">
Montecino Soto, L. A. (2005). <em>Representaciones discursivas de la pobreza en la prensa chilena</em>.
</div>
<div id="ref-moscovici1979" class="csl-entry" role="listitem">
Moscovici, S. (1984). The phenomenon of social representations. In R. M. Farr &amp; S. Moscovici (Eds.), <em>Social representations</em>. Cambridge University Press.
</div>
<div id="ref-palazzo2010b" class="csl-entry" role="listitem">
Palazzo, M. G. (2009). El ciberdiscurso juvenil: Representaciones sociales del desconcierto, la censura y la aceptaci<span>ó</span>n. <em>Esp<span>é</span>culo. Revista de Estudios Literarios</em>, <em>41</em>. <a href="https://webs.ucm.es/info/especulo/numero41/">https://webs.ucm.es/info/especulo/numero41/</a>
</div>
<div id="ref-palazzo2010a" class="csl-entry" role="listitem">
Palazzo, M. G. (2010). Aspectos comunicativos del ciberdiscurso juvenil. Consideraciones te<span>ó</span>ricas. <em>Revista Argentina de Estudios de Juventud</em>, 1–22. <a href="https://www.aacademica.org/gabriela.palazzo/59">https://www.aacademica.org/gabriela.palazzo/59</a>
</div>
<div id="ref-raiter2002" class="csl-entry" role="listitem">
<span class="nocase">Raiter, A., Zullo, J., et al.</span> (2002). <em>Representaciones sociales</em>. Eudeba.
</div>
<div id="ref-robertson1995" class="csl-entry" role="listitem">
Robertson, R. (1995). Glocalization: Time-space and homogeneity-heterogeneity. In M. Featherstone, S. Lash, &amp; R. Robertson (Eds.), <em>Global modernities</em> (pp. 25–44). SAGE Publications.
</div>
<div id="ref-sibilia2008" class="csl-entry" role="listitem">
Sibilia, P. (2008). <em>La intimidad como espect<span>á</span>culo</em>. Fondo de Cultura Econ<span>ó</span>mica.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04_genero.html" class="pagination-link" aria-label="El videoblog como género ciberdiscursivo">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">El videoblog como género ciberdiscursivo</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06_trayectorias.html" class="pagination-link" aria-label="Trayectorias identitarias en el videoblog juvenil">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trayectorias identitarias en el videoblog juvenil</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>