<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo – El videoblog como espacio social practicado: discursos, narrativas e identidades juveniles en YouTube Argentina (2012-2016)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08_conclusiones.html" rel="next">
<link href="./06_trayectorias.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fa1ce29839742e4f64bd70bd814635ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="estilos.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_genero.html">Análisis y resultados</a></li><li class="breadcrumb-item"><a href="./07_lenguaje.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">El videoblog como espacio social practicado: discursos, narrativas e identidades juveniles en YouTube Argentina (2012-2016)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dedicatoria</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resumen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agradecimientos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Agradecimientos</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">INTRODUCCIÓN</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_mtya.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Marco Teórico y Antecedentes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_metod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Metodología</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Análisis y resultados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_genero.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">El videoblog como género ciberdiscursivo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_identidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Identidades juveniles digitales: representaciones, narrativas y subjetividades en el videoblog</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_trayectorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trayectorias identitarias en el videoblog juvenil</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_lenguaje.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Cierre</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Referencias Bibliográficas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias Bibliográficas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Anexos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_a_youtubers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo A: Youtubers del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_b_glosario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Anexo B: Glosario de términos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_c_corpus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo D: Listado completo del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_d_transcripciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo E: Transcripciones del corpus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_e_materiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo F: Materiales de investigación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo_f_topicmodeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo G: Modelado de tópicos — resultados explorativos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./indice_tematico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Índice temático</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">7.1</span> Introducción</a></li>
  <li><a href="#marco-conceptual" id="toc-marco-conceptual" class="nav-link" data-scroll-target="#marco-conceptual"><span class="header-section-number">7.2</span> Marco conceptual</a>
  <ul class="collapse">
  <li><a href="#variación-lingüística-y-variedades-del-español-argentino" id="toc-variación-lingüística-y-variedades-del-español-argentino" class="nav-link" data-scroll-target="#variación-lingüística-y-variedades-del-español-argentino"><span class="header-section-number">7.2.1</span> Variación lingüística y variedades del español argentino</a></li>
  <li><a href="#nivelación-dialectal" id="toc-nivelación-dialectal" class="nav-link" data-scroll-target="#nivelación-dialectal"><span class="header-section-number">7.2.2</span> Nivelación dialectal</a></li>
  <li><a href="#del-netspeak-al-registro-pragmático-discursivo" id="toc-del-netspeak-al-registro-pragmático-discursivo" class="nav-link" data-scroll-target="#del-netspeak-al-registro-pragmático-discursivo"><span class="header-section-number">7.2.3</span> Del netspeak al registro pragmático-discursivo</a></li>
  <li><a href="#glocalidad-lingüística-en-espacios-digitales" id="toc-glocalidad-lingüística-en-espacios-digitales" class="nav-link" data-scroll-target="#glocalidad-lingüística-en-espacios-digitales"><span class="header-section-number">7.2.4</span> Glocalidad lingüística en espacios digitales</a></li>
  </ul></li>
  <li><a href="#variación-sociodialectal-y-estrategias-de-nivelación" id="toc-variación-sociodialectal-y-estrategias-de-nivelación" class="nav-link" data-scroll-target="#variación-sociodialectal-y-estrategias-de-nivelación"><span class="header-section-number">7.3</span> Variación sociodialectal y estrategias de nivelación</a>
  <ul class="collapse">
  <li><a href="#lionel-ferro-la-neutralización" id="toc-lionel-ferro-la-neutralización" class="nav-link" data-scroll-target="#lionel-ferro-la-neutralización"><span class="header-section-number">7.3.1</span> Lionel Ferro: la neutralización</a></li>
  <li><a href="#julián-serrano-del-litoral-entrerriano-al-estándar-bonaerense" id="toc-julián-serrano-del-litoral-entrerriano-al-estándar-bonaerense" class="nav-link" data-scroll-target="#julián-serrano-del-litoral-entrerriano-al-estándar-bonaerense"><span class="header-section-number">7.3.2</span> Julián Serrano: del litoral entrerriano al estándar bonaerense</a></li>
  <li><a href="#la-paradoja-de-la-nivelación-y-la-hegemonía-del-estándar-porteño" id="toc-la-paradoja-de-la-nivelación-y-la-hegemonía-del-estándar-porteño" class="nav-link" data-scroll-target="#la-paradoja-de-la-nivelación-y-la-hegemonía-del-estándar-porteño"><span class="header-section-number">7.3.3</span> La paradoja de la nivelación y la hegemonía del estándar porteño</a></li>
  <li><a href="#evidencia-léxica-frecuencia-de-marcadores-regionales-y-de-plataforma" id="toc-evidencia-léxica-frecuencia-de-marcadores-regionales-y-de-plataforma" class="nav-link" data-scroll-target="#evidencia-léxica-frecuencia-de-marcadores-regionales-y-de-plataforma"><span class="header-section-number">7.3.4</span> Evidencia léxica: frecuencia de marcadores regionales y de plataforma</a></li>
  <li><a href="#evolución-diacrónica-el-léxico-como-indicador-de-profesionalización" id="toc-evolución-diacrónica-el-léxico-como-indicador-de-profesionalización" class="nav-link" data-scroll-target="#evolución-diacrónica-el-léxico-como-indicador-de-profesionalización"><span class="header-section-number">7.3.5</span> Evolución diacrónica: el léxico como indicador de profesionalización</a></li>
  </ul></li>
  <li><a href="#la-construcción-del-registro-pragmático-discursivo" id="toc-la-construcción-del-registro-pragmático-discursivo" class="nav-link" data-scroll-target="#la-construcción-del-registro-pragmático-discursivo"><span class="header-section-number">7.4</span> La construcción del registro pragmático-discursivo</a>
  <ul class="collapse">
  <li><a href="#léxico-emergente-de-la-intuición-a-la-profesionalización" id="toc-léxico-emergente-de-la-intuición-a-la-profesionalización" class="nav-link" data-scroll-target="#léxico-emergente-de-la-intuición-a-la-profesionalización"><span class="header-section-number">7.4.1</span> Léxico emergente: de la intuición a la profesionalización</a></li>
  <li><a href="#la-ritualización-de-la-interacción" id="toc-la-ritualización-de-la-interacción" class="nav-link" data-scroll-target="#la-ritualización-de-la-interacción"><span class="header-section-number">7.4.2</span> La ritualización de la interacción</a></li>
  <li><a href="#la-gestión-de-la-periodicidad-la-disculpa-como-evento-de-excepción" id="toc-la-gestión-de-la-periodicidad-la-disculpa-como-evento-de-excepción" class="nav-link" data-scroll-target="#la-gestión-de-la-periodicidad-la-disculpa-como-evento-de-excepción"><span class="header-section-number">7.4.3</span> La gestión de la periodicidad: la disculpa como evento de excepción</a></li>
  <li><a href="#el-agradecimiento-performativo-y-la-consagración-del-número" id="toc-el-agradecimiento-performativo-y-la-consagración-del-número" class="nav-link" data-scroll-target="#el-agradecimiento-performativo-y-la-consagración-del-número"><span class="header-section-number">7.4.4</span> El agradecimiento performativo y la consagración del número</a></li>
  <li><a href="#estrategias-de-cortesía-de-la-transgresión-rebelde-a-la-marca-profesional" id="toc-estrategias-de-cortesía-de-la-transgresión-rebelde-a-la-marca-profesional" class="nav-link" data-scroll-target="#estrategias-de-cortesía-de-la-transgresión-rebelde-a-la-marca-profesional"><span class="header-section-number">7.4.5</span> Estrategias de cortesía: de la transgresión rebelde a la marca profesional</a></li>
  </ul></li>
  <li><a href="#del-mito-de-la-variedad-web-al-registro-situado" id="toc-del-mito-de-la-variedad-web-al-registro-situado" class="nav-link" data-scroll-target="#del-mito-de-la-variedad-web-al-registro-situado"><span class="header-section-number">7.5</span> Del mito de la variedad web al registro situado</a></li>
  <li><a href="#conclusiones-parciales-del-capítulo" id="toc-conclusiones-parciales-del-capítulo" class="nav-link" data-scroll-target="#conclusiones-parciales-del-capítulo"><span class="header-section-number">7.6</span> Conclusiones parciales del capítulo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_genero.html">Análisis y resultados</a></li><li class="breadcrumb-item"><a href="./07_lenguaje.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Prácticas sociolingüísticas en el videoblog: variación dialectal y registro pragmático-discursivo</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">7.1</span> Introducción</h2>
<p>El videoblog como género ciberdiscursivo plantea interrogantes específicos desde la sociolingüística: ¿cómo se manifiesta la variación dialectal del español en un espacio digital transnacional? ¿Los youtubers conservan rasgos de sus variedades regionales o tienden a neutralizarlos? ¿Existe algo así como una “variedad web” del español o simplemente asistimos a la emergencia de un registro pragmático propio del género?</p>
<p>Estas preguntas cobran particular relevancia en el caso argentino, donde conviven múltiples variedades sub-nacionales del español —noroandino, litoral, cuyano, patagónico, rioplatense—, cada una con rasgos fonético-fonológicos, morfosintácticos y léxicos distintivos <span class="citation" data-cites="vidal1964 fontanella2004">(<a href="referencias.html#ref-fontanella2004" role="doc-biblioref">Fontanella de Weinberg, 2004</a>; <a href="referencias.html#ref-vidal1964" role="doc-biblioref">Vidal de Battini, 1964</a>)</span>. Sin embargo, la producción de contenido en YouTube impone condiciones específicas: los creadores buscan maximizar su alcance, construir audiencias transnacionales y participar de comunidades de práctica que trascienden fronteras geográficas. Esto genera tensiones entre la autenticidad local —mostrar “quién soy realmente”— y la proyección global —ser entendido y valorado por audiencias diversas.</p>
<p>Los estudios previos sobre lenguaje en internet han oscilado entre posiciones maximalistas, que postulan la existencia de nuevas “variedades digitales” <span class="citation" data-cites="crystal2002">(<a href="referencias.html#ref-crystal2002" role="doc-biblioref">Crystal, 2001</a>)</span>, y enfoques más cautelosos que señalan que las particularidades observadas responden más a registros situados que a variedades lingüísticas autónomas <span class="citation" data-cites="androutsopoulos2013 cerruti2013">(<a href="referencias.html#ref-androutsopoulos2013" role="doc-biblioref">Androutsopoulos, 2013</a>; <a href="referencias.html#ref-cerruti2013" role="doc-biblioref">Cerruti &amp; Onesti, 2013</a>)</span>. En el caso del español, trabajos como los de <span class="citation" data-cites="alcantara2016">Alcántara Plá (<a href="referencias.html#ref-alcantara2016" role="doc-biblioref">2016</a>)</span> sobre neologismos tecnológicos, <span class="citation" data-cites="giammatteo2012">Giammatteo &amp; Albano (<a href="referencias.html#ref-giammatteo2012" role="doc-biblioref">2012</a>)</span> sobre léxico digital, y <span class="citation" data-cites="palazzo2010a">Palazzo (<a href="referencias.html#ref-palazzo2010a" role="doc-biblioref">2010</a>)</span> y <span class="citation" data-cites="palazzo2010b">Palazzo (<a href="referencias.html#ref-palazzo2010b" role="doc-biblioref">2009</a>)</span> sobre ciberdiscurso juvenil, han documentado fenómenos específicos sin llegar a postular la existencia de una “variedad web” consolidada.</p>
<p>Nuestra posición es moderada y empíricamente fundada: no existe una “variedad web” autónoma del español, pero los youtubers desarrollan un registro pragmático-discursivo específico del género vlog, con estrategias de nivelación dialectal motivadas por la búsqueda de alcance transnacional. Este registro se caracteriza por cinco rasgos: (1) tendencia a la neutralización de rasgos dialectales marcados, especialmente fonético-fonológicos; (2) conservación selectiva de marcas identitarias locales, principalmente léxico y referencias culturales; (3) emergencia de léxico específico relacionado con la plataforma y las prácticas de comunidad; (4) ritualización de actos de habla propios del género; y (5) estrategias de cortesía y anticortesía vinculadas al ciberdiscurso juvenil.</p>
</section>
<section id="marco-conceptual" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="marco-conceptual"><span class="header-section-number">7.2</span> Marco conceptual</h2>
<section id="variación-lingüística-y-variedades-del-español-argentino" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="variación-lingüística-y-variedades-del-español-argentino"><span class="header-section-number">7.2.1</span> Variación lingüística y variedades del español argentino</h3>
<p>La sociolingüística contemporánea distingue entre variedad lingüística —configuración estable de rasgos en todos los niveles del sistema que caracteriza a una comunidad de hablantes— y registro —selección de rasgos motivada por la situación comunicativa, el canal y las relaciones entre interlocutores <span class="citation" data-cites="halliday1978 moreno1999">(<a href="referencias.html#ref-halliday1978" role="doc-biblioref">Halliday, 1978</a>; <a href="referencias.html#ref-moreno1999" role="doc-biblioref">Moreno Fernández, 1999</a>)</span>. Esta distinción es crucial para analizar las prácticas lingüísticas en YouTube: ¿los youtubers “hablan en internet” como hablan una variedad dialectal, o más bien seleccionan recursos según el contexto comunicativo del vlog?</p>
<p>El español de Argentina es una lengua policéntrica <span class="citation" data-cites="schneider2008">(<a href="referencias.html#ref-schneider2008" role="doc-biblioref">Schneider &amp; Foot, 2007</a>)</span> con múltiples variedades sub-nacionales. <span class="citation" data-cites="fontanella2004">Fontanella de Weinberg (<a href="referencias.html#ref-fontanella2004" role="doc-biblioref">2004</a>)</span> identifica cinco grandes regiones dialectales: (1) Noroeste, (2) Noreste/Litoral, (3) Cuyo, (4) Patagonia, y (5) Región Pampeana/Rioplatense. De estas, la variedad rioplatense —especialmente en su forma bonaerense— funciona como estándar de facto en medios masivos, entretenimiento y comunicación transnacional, asociada a prestigio y modernidad urbana.</p>
<p><strong>La variedad rioplatense (Buenos Aires)</strong> se caracteriza por yeísmo rehilado ([ʒ] o [ʃ]), aspiración moderada o ausencia de aspiración de /s/ final, entonación con tonemas ascendentes en declarativas, voseo pronominal y verbal (<em>vos tenés</em>), y léxico porteño (<em>bondi</em>, <em>laburo</em>, <em>pibe</em>). <strong>La variedad del Litoral (Entre Ríos)</strong> es zona de transición: yeísmo rehilado, pero menos marcado que en Buenos Aires, aspiración de /s/ final más frecuente, entonación más pausada. <strong>La variedad de Cuyo/Centro (Córdoba)</strong> se caracteriza por entonación muy marcada con alargamiento de vocales tónicas, aspiración fuerte de /s/ implosiva ([h]), yeísmo, pero no rehilado, y léxico regional distintivo (<em>cuarteto</em>, <em>fernet</em>, <em>culiau</em>). La variedad cordobesa es altamente reconocible en Argentina y objeto de representaciones culturales estereotipadas. La pregunta que atraviesa este capítulo es: ¿qué hacen los youtubers no-bonaerenses con estas marcas dialectales al insertarse en un espacio digital transnacional?</p>
</section>
<section id="nivelación-dialectal" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="nivelación-dialectal"><span class="header-section-number">7.2.2</span> Nivelación dialectal</h3>
<p><span class="citation" data-cites="trudgill2007">Trudgill (<a href="referencias.html#ref-trudgill2007" role="doc-biblioref">2000</a>)</span> definen la nivelación dialectal como el proceso por el que “un número de formas variantes fonético-fonológicas, léxicas o gramaticales que están presentes en la mixtura dialectal se reducen a uno menor, como consecuencia de la fijación, de forma que los dialectos o acentos implicados en la mixtura pierden sus rasgos distintivos y se hacen cada vez más similares” (p.&nbsp;234). Documentado en contextos de migración y contacto dialectal intenso, este proceso también puede darse en espacios digitales donde hablantes de diferentes variedades interactúan constantemente. La nivelación no es automática ni neutral: responde a valoraciones sociales sobre prestigio, inteligibilidad y pertenencia. Como señala <span class="citation" data-cites="fasold1996">Fasold (<a href="referencias.html#ref-fasold1996" role="doc-biblioref">1990</a>)</span>, los hablantes desarrollan actitudes de lealtad o deslealtad lingüística que motivan decisiones de mantenimiento o cambio de variedad.</p>
<p>En el caso de YouTube hispanohablante, la nivelación hacia variedades de mayor alcance se ve reforzada por factores materiales de la plataforma: los algoritmos premian el alcance transnacional, las métricas valoran audiencias amplias, y las estrategias de monetización favorecen contenidos “universalizables”. Los youtubers enfrentan una tensión: conservar rasgos locales puede limitar audiencia, pero aumenta autenticidad; neutralizar puede ampliar alcance, pero genera acusaciones de “vendido” o “falso”.</p>
</section>
<section id="del-netspeak-al-registro-pragmático-discursivo" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="del-netspeak-al-registro-pragmático-discursivo"><span class="header-section-number">7.2.3</span> Del netspeak al registro pragmático-discursivo</h3>
<p><span class="citation" data-cites="crystal2002">Crystal (<a href="referencias.html#ref-crystal2002" role="doc-biblioref">2001</a>)</span> acuñó el término <em>netspeak</em> para referirse a las formas lingüísticas emergentes en internet, postulando que constituirían una “nueva variedad” del lenguaje. Sin embargo, esta tesis ha sido ampliamente cuestionada. <span class="citation" data-cites="cerruti2013">Cerruti &amp; Onesti (<a href="referencias.html#ref-cerruti2013" role="doc-biblioref">2013</a>)</span> argumentan que los rasgos observados en comunicación digital —abreviaturas, emoticones, léxico específico— no configuran una variedad autónoma porque no presentan gramática distintiva, no poseen fonología propia, el léxico especializado es limitado y específico de contextos, y los rasgos no son estables, sino altamente dependientes de plataforma y género.</p>
<p><span class="citation" data-cites="thurlow2011">Thurlow &amp; Mroczek (<a href="referencias.html#ref-thurlow2011" role="doc-biblioref">2011</a>)</span> ofrece una perspectiva alternativa más productiva: en lugar de “variedades digitales”, deberíamos hablar de creatividad lingüística juvenil situada en contextos tecnológicos. Los jóvenes no “hablan internet”; despliegan recursos expresivos adaptados a las <em>affordances</em> de cada plataforma y género. Esta perspectiva conecta con el concepto de ciberdiscurso juvenil de <span class="citation" data-cites="palazzo2010a">Palazzo (<a href="referencias.html#ref-palazzo2010a" role="doc-biblioref">2010</a>)</span>, quien señala que “para los jóvenes, la adecuación y la coherencia no dependen del ajuste a normas prescriptivas, ya que se privilegia lo comunicativo en el sentido de conexión, interacción, acercamiento e intersubjetividad en un marco que recupera los aspectos lúdicos del intercambio verbal”.</p>
<p>Desde esta perspectiva, proponemos entender las prácticas lingüísticas en vlogs como un registro pragmático-discursivo: una configuración de rasgos lingüísticos motivada por su campo (narrativas identitarias, extimidad, vida cotidiana juvenil), su tenor (vínculo parasocial asimétrico, pero íntimo con audiencia) y su modo (comunicación multimodal, audiovisual, diferida, pero conversacional). Este registro comparte rasgos con otros géneros juveniles —conversación entre amigos, relatos personales— pero incorpora elementos específicos de la plataforma: léxico técnico, rituales de comunidad, llamados a la acción.</p>
</section>
<section id="glocalidad-lingüística-en-espacios-digitales" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="glocalidad-lingüística-en-espacios-digitales"><span class="header-section-number">7.2.4</span> Glocalidad lingüística en espacios digitales</h3>
<p>El concepto de glocalidad <span class="citation" data-cites="robertson1995 feixa2006 garciacanclini1995">(<a href="referencias.html#ref-feixa2006" role="doc-biblioref">Feixa, 2006</a>; <a href="referencias.html#ref-garciacanclini1995" role="doc-biblioref">García Canclini, 1995</a>; <a href="referencias.html#ref-robertson1995" role="doc-biblioref">Robertson, 1995</a>)</span> resulta fundamental para entender las prácticas lingüísticas en YouTube. Los youtubers operan simultáneamente en lo global —plataforma transnacional, audiencias internacionales, comunidad hispanohablante amplia— y en lo local —referencias culturales argentinas, léxico regional, temas situados. Esta doble inscripción genera estrategias específicas.</p>
<p>La <strong>neutralización formal / particularización temática</strong> nivelan pronunciación y léxico hacia formas más estándar, pero conservan referencias culturales locales (clubes de fútbol, programas de TV argentinos). La <strong>marcación explícita de localismo</strong> transforma la marca dialectal en recurso performativo: cuando se usa léxico muy regional, se lo explica mediante placas escritas, paréntesis orales (“o sea, bondi, el colectivo”) o humor autoconsciente. La <strong>alternancia <em>code-switching</em> identitaria</strong> aumenta la neutralización en contextos de mayor proyección internacional (colaboraciones con youtubers extranjeros) y refuerza marcas regionales en contextos de cercanía con audiencia local.</p>
<div id="tbl-corpus-dialectal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-corpus-dialectal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;7.1: Youtubers del corpus, origen geográfico y variedad dialectal.
</figcaption>
<div aria-describedby="tbl-corpus-dialectal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Youtuber</strong></th>
<th style="text-align: left;"><strong>Origen</strong></th>
<th style="text-align: left;"><strong>Variedad dialectal</strong></th>
<th style="text-align: left;"><strong>Suscriptores (2016)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lucas Castel</td>
<td style="text-align: left;">Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~2.5M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Julián Serrano</td>
<td style="text-align: left;">Entre Ríos</td>
<td style="text-align: left;">Litoral/Rioplatense ⟳</td>
<td style="text-align: left;">~3M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gonzalo Fonseca</td>
<td style="text-align: left;">Uruguay/Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~1.5M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lionel Ferro</td>
<td style="text-align: left;">Córdoba</td>
<td style="text-align: left;">Centro (cordobés) ⟳</td>
<td style="text-align: left;">~1.2M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mariano Bondar</td>
<td style="text-align: left;">Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~2M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gonzalo Goette</td>
<td style="text-align: left;">Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~1.8M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elchuiuical</td>
<td style="text-align: left;">Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~1.5M</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mica Suárez</td>
<td style="text-align: left;">Buenos Aires</td>
<td style="text-align: left;">Rioplatense</td>
<td style="text-align: left;">~1.6M</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Las <strong>variables sociolingüísticas</strong> analizadas incluyen: rasgos fonético-fonológicos identificables (aspiración de /s/, tipo de yeísmo, entonación), léxico regional vs.&nbsp;estándar vs.&nbsp;específico de plataforma, formas de tratamiento (vos/tú, ustedes/vosotros) y referencias metalingüísticas a la propia variedad. Las <strong>variables pragmático-discursivas</strong> incluyen: actos de habla ritualizados (saludos, despedidas, disculpas, agradecimientos, promesas), llamados a la acción (suscribirse, comentar, compartir), deícticos de construcción de comunidad, y estrategias de cortesía y anticortesía. Las <strong>variables temporales</strong> incluyen la evolución diacrónica (videos 2012 vs.&nbsp;2016) y los cambios en rasgos dialectales a lo largo del tiempo.</p>
<p>El análisis procede en dos movimientos: primero, el análisis en profundidad de los dos casos con variación sociodialectal evidente (Ferro y Serrano); segundo, el análisis transversal de todo el corpus para identificar el registro pragmático-discursivo común.</p>
</section>
</section>
<section id="variación-sociodialectal-y-estrategias-de-nivelación" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="variación-sociodialectal-y-estrategias-de-nivelación"><span class="header-section-number">7.3</span> Variación sociodialectal y estrategias de nivelación</h2>
<p>Este apartado focaliza el análisis en los dos youtubers del corpus cuyas variedades de origen difieren significativamente del estándar rioplatense bonaerense: Lionel Ferro (Córdoba) y Julián Serrano (Entre Ríos).</p>
<section id="lionel-ferro-la-neutralización" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="lionel-ferro-la-neutralización"><span class="header-section-number">7.3.1</span> Lionel Ferro: la neutralización</h3>
<p>El caso de Lionel Ferro constituye el ejemplo paradigmático de lo que podríamos denominar una <strong>nivelación dialectal por profesionalización</strong>. Su IGL más alto del corpus (0.52) encuentra su correlato material en una gestión del habla orientada sistemáticamente hacia la desmarcación regional. Si en su trayectoria identitaria Ferro construye al “yo” como un producto mediático consciente, en el plano sociolingüístico esta operación se traduce en una asepsia deliberada de los rasgos cordobeses, sacrificando la “autenticidad territorial” en pos de una inteligibilidad transnacional apta para los estándares de la industria del entretenimiento global.</p>
<p>El análisis de su producción temprana —en particular el video “Ruggero Pasquarelli besa el pie de Lionel Ferro” (2014)— revela que el proceso de neutralización no fue gradual, sino fundacional. A pesar de ser nativo de una zona dialectal con marcas fonético-fonológicas de alta saliencia perceptiva —aspiración intensa de /s/ implosiva, alargamiento vocálico tónico y curva entonativa circunfleja distintiva—, Ferro exhibe desde sus inicios una variedad ya estandarizada hacia el modelo rioplatense urbano. Frases como “me los afeito” o “acostumbrate” se enuncian con una prosodia que elide por completo la musicalidad cordobesa esperable. Más reveladora aún es la apertura de su video VID 40 (2016):</p>
<blockquote class="blockquote">
<p>“No, mentira, soy Lío. […] Bueno, estoy acá en el camarín solo y aburrido. No sé qué hacer. Así que voy a subir un video a YouTube mostrando los Snapchat que hago. ¿Qué les parece?” (VID 40, 0:03-0:22)</p>
</blockquote>
<p>Ni la entonación, ni el léxico, ni la construcción sintáctica delatan procedencia cordobe­sa. El “acá en el camarín” podría ser dicho por cualquier joven de Capital Federal. La neutralización ya no es esfuerzo: es <em>habitus</em>.</p>
<p>Esta decisión lingüística no debe leerse como una “pérdida” pasiva por contacto dialectal tras su mudanza a la capital, sino como una estrategia de acomodación proactiva. Ferro comprende tempranamente que el acento regional, en la economía simbólica de los medios masivos, funciona frecuentemente como marcador de humor costumbrista o de periferia cultural, roles que colisionan con su aspiración de posicionarse como galán juvenil internacional. Al borrar las huellas de su origen fonético, “limpia” la interfaz comunicativa para maximizar la señal global.</p>
<p>La paradoja de esta operación reside en cómo afecta su IAP. A diferencia de creadores como Lucas Castel, cuya autenticidad reside en la “suciedad” vital de su habla barrial, la autenticidad de Ferro es, paradójicamente, su artificialidad transparente: su habla no pretende ser espontánea, sino correcta y eficaz. La ausencia de marcadores coloquiales cordobeses y la adopción de un registro léxico estándar refuerzan su identidad de “producto profesional”. La evolución diacrónica hacia 2016 —visible en videos como “Les presento al amor de mi vida”— confirma la consolidación de este registro: la neutralización deja de ser un esfuerzo performático para convertirse en <em>habitus</em> mediático. Ferro logra así una “glocalidad desanclada”: conserva referencias temáticas a su origen (menciona Córdoba, el fernet) como meros datos biográficos, pero vacía su habla de la materialidad sonora de ese territorio.</p>
</section>
<section id="julián-serrano-del-litoral-entrerriano-al-estándar-bonaerense" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="julián-serrano-del-litoral-entrerriano-al-estándar-bonaerense"><span class="header-section-number">7.3.2</span> Julián Serrano: del litoral entrerriano al estándar bonaerense</h3>
<p>Si Lionel Ferro ilustra la neutralización hacia un estándar global desterritorializado, la trayectoria de Julián Serrano ejemplifica un proceso diferente: la nivelación hacia el estándar de prestigio nacional. Su desplazamiento desde la variedad litoral entrerriana hacia la norma culta rioplatense bonaerense no busca borrar la argentinidad (como en Ferro), sino centralizarla, alineando su habla con el centro de poder mediático y simbólico del país. Esta estrategia es coherente con su perfil en la red: el “conector universal” del ecosistema local, con el ICP más alto del corpus, no puede sonar “extranjero” pero tampoco puede permitirse las marcas regionales que limitarían su ascenso al <em>star-system</em> televisivo.</p>
<p>El punto de partida de esta curva evolutiva se encuentra en sus producciones tempranas. En “FILOSOFANDO (?)” (2012), un Serrano adolescente performa una identidad de “rebelde sin causa” mediante una anticortesía lingüística sistemática: alta densidad de vocabulario vulgar y coloquialismos agresivos (“tipo un verga”, “una mierda”, “la p*** que te pario”) que funcionan como marcadores de pertenencia subcultural. En este estadio, la variedad dialectal entrerriana —con su aspiración de /s/ más frecuente y una entonación pausada— se amalgama con un registro de “bajos fondos” juveniles que garantiza legitimidad ante sus pares, pero que resulta inviable para el mercado masivo.</p>
<p>El quiebre se produce con su mudanza a Buenos Aires y su inserción en la industria televisiva (<em>Aliados</em>, Cris Morena). El contraste con videos tardíos como “Viaje a México con otros creadores” (2016) es drástico: desaparecen los improperios como muletillas constantes, se adopta el léxico técnico de la “economía de creadores” (“grabar”, “contenido”, “equipo”). Fonéticamente, Serrano no adopta el neutro latino de Ferro; adopta la prosodia del joven exitoso de Buenos Aires. Su yeísmo se rehíla con mayor nitidez (acercándose al [ʃ] porteño) y su entonación adquiere el ritmo urbano capitalino.</p>
<p>La evidencia más contundente de que estamos ante una competencia sociolingüística activa aparece en el video familiar de 2017, analíticamente crucial aunque fuera del recorte principal del corpus: al interactuar con sus padres y hermana, quienes conservan intactos los rasgos entrerrianos, Serrano no “vuelve” a su variedad original. Este desajuste pragmático revela que la nivelación se ha sedimentado como <em>habitus</em>: el estándar bonaerense ya no es una máscara, sino su nueva piel lingüística. Al sostener esta variedad incluso en la intimidad familiar, Serrano performa la distancia que ha recorrido: el lenguaje se convierte en la prueba material de su movilidad social ascendente.</p>
</section>
<section id="la-paradoja-de-la-nivelación-y-la-hegemonía-del-estándar-porteño" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="la-paradoja-de-la-nivelación-y-la-hegemonía-del-estándar-porteño"><span class="header-section-number">7.3.3</span> La paradoja de la nivelación y la hegemonía del estándar porteño</h3>
<p>El análisis contrastivo de ambas trayectorias permite postular un patrón estructural en la gestión de la variedad dialectal en el ecosistema YouTube argentino. Ambos casos revelan una <strong>disociación táctica entre forma y contenido</strong>: neutralización formal de rasgos fonético-fonológicos marcados, pero conservación temática de referencias de origen. Esta maniobra resuelve la tensión constitutiva del IGL: mientras la limpieza fonética garantiza la inteligibilidad ampliada para audiencias transnacionales, la cita recurrente a la cultura local —el fernet, el club de barrio, las costumbres provincianas— preserva la legitimidad de origen. Aunque el acento se pierda, la “patria chica” de la que provienen se convierte en narración: la identidad se vuelve contenido.</p>
<p>Además, la movilidad geográfica acelera la nivelación El desplazamiento físico de la periferia al centro (Córdoba/Entre Ríos → Buenos Aires) no es solo un cambio de domicilio, sino una inmersión en el mercado lingüístico dominante. La profesionalización del rol —que empuja a los creadores desde el amateurismo inicial hacia la integración en la industria de medios— demanda esta nivelación como requisito de entrada para la colaboración internacional y el contrato publicitario.</p>
<p>El hallazgo político más relevante es que la dirección de esta nivelación no es hacia un “español neutro latinoamericano” —ese constructo artificial del doblaje y la CNN—, sino específicamente hacia el rioplatense bonaerense Incluso en espacios digitales supuestamente “democráticos” y desterritorializados como YouTube, la variedad de Buenos Aires funciona como el estándar de facto al que aspiran los creadores provinciales para legitimar su ascenso. El “éxito” en YouTube Argentina no suena a internet; suena a Buenos Aires.</p>
</section>
<section id="evidencia-léxica-frecuencia-de-marcadores-regionales-y-de-plataforma" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="evidencia-léxica-frecuencia-de-marcadores-regionales-y-de-plataforma"><span class="header-section-number">7.3.4</span> Evidencia léxica: frecuencia de marcadores regionales y de plataforma</h3>
<p>Para respaldar cuantitativamente las observaciones cualitativas precedentes, se realizó un análisis de frecuencia léxica sobre las transcripciones completas de los 80 videos del corpus, cruzando la ocurrencia de marcadores coloquiales rioplatenses y léxico de plataforma con la identidad del creador. La <a href="#tbl-frecuencias-lexicas" class="quarto-xref">Tabla&nbsp;<span>7.2</span></a> presenta las frecuencias normalizadas por cada 1000 palabras, lo que permite la comparabilidad entre creadores con diferente volumen de producción verbal.</p>
<div id="tbl-frecuencias-lexicas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frecuencias-lexicas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;7.2: Frecuencia de marcadores léxicos regionales y de plataforma por youtuber (ocurrencias cada 1000 palabras). Fuente: análisis computacional sobre transcripciones del corpus.
</figcaption>
<div aria-describedby="tbl-frecuencias-lexicas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Marcador</th>
<th style="text-align: center;">L. Castel</th>
<th style="text-align: center;">J. Serrano</th>
<th style="text-align: center;">M. Suárez</th>
<th style="text-align: center;">G. Fonseca</th>
<th style="text-align: center;">G. Goette</th>
<th style="text-align: center;">M. Bondar</th>
<th style="text-align: center;">L. Ferro</th>
<th style="text-align: center;">Elchuiuical</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><em>boludo/a</em></td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">2.2</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;"><strong>11.6</strong></td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">1.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>tipo</em> (filler)</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>chabón</em></td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;"><strong>2.2</strong></td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>pibe/s</em></td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>re</em> (intensif.)</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;"><strong>1.4</strong></td>
<td style="text-align: center;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>bueno</em> (filler)</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">6.6</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">6.2</td>
<td style="text-align: center;"><strong>10.2</strong></td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">8.3</td>
<td style="text-align: center;">4.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>suscri-</em></td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;"><strong>1.3</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>like/me gusta</em></td>
<td style="text-align: center;"><strong>2.8</strong></td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><em>video/s</em></td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: center;"><strong>8.1</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>comentar-</em></td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;"><strong>1.5</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total palabras</td>
<td style="text-align: center;">12.339</td>
<td style="text-align: center;">13.471</td>
<td style="text-align: center;">18.760</td>
<td style="text-align: center;">12.600</td>
<td style="text-align: center;">10.665</td>
<td style="text-align: center;">11.080</td>
<td style="text-align: center;">12.169</td>
<td style="text-align: center;">8.652</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La tabla revela varios patrones significativos. Primero, la asimetría en el uso de <em>boludo/a</em>: Gonzalo Goette multiplica por diez la frecuencia de cualquier otro creador (11.6‰), consistente con su estilo de confrontación callejera, mientras que Lionel Ferro prácticamente lo evita (0.2‰), coherente con su estrategia de neutralización hacia un registro <em>brand-safe</em>. Segundo, el léxico de plataforma (<em>suscri-</em>, <em>video</em>, <em>comentar-</em>) muestra concentraciones más altas en Elchuiuical, el creador más explícitamente metacomunicativo del corpus, y menores en Serrano y Bondar, quienes integran los llamados a la acción de forma más naturalizada en el flujo discursivo. Tercero, el intensificador <em>re</em> —marcador coloquial rioplatense por excelencia— está presente en todos los creadores, pero alcanza su pico paradójicamente en Ferro (1.4‰), lo que sugiere que la nivelación dialectal opera selectivamente: se borran los rasgos fonéticos, pero se conservan las partículas pragmáticas de alta frecuencia, aquellas que funcionan como <em>shibboleths</em> de argentinidad sin connotar una procedencia regional específica.</p>
</section>
<section id="evolución-diacrónica-el-léxico-como-indicador-de-profesionalización" class="level3" data-number="7.3.5">
<h3 data-number="7.3.5" class="anchored" data-anchor-id="evolución-diacrónica-el-léxico-como-indicador-de-profesionalización"><span class="header-section-number">7.3.5</span> Evolución diacrónica: el léxico como indicador de profesionalización</h3>
<p>El contraste entre los primeros y los últimos cinco videos de cada creador permite trazar la curva de profesionalización lingüística. Los datos más reveladores emergen de tres tendencias convergentes:</p>
<ol type="1">
<li><p><strong>Intensificación del coloquialismo en los creadores consolidados.</strong> Contra lo esperable, el uso de <em>boludo/a</em> aumenta en la etapa tardía de Goette (de 2.1‰ a 18.1‰), Serrano (de 0.5‰ a 3.3‰) y Bondar (de 1.4‰ a 4.8‰). Esto sugiere que la “licencia para el exceso” coloquial es un privilegio de la audiencia consolidada: a mayor capital simbólico acumulado, mayor libertad para transgredir las normas de cortesía sin riesgo de pérdida de audiencia.</p></li>
<li><p><strong>Descenso del léxico metadiscursivo de plataforma.</strong> La frecuencia de <em>suscri-</em> cae en casi todos los creadores entre la etapa inicial y la final (Elchuiuical: de 2.5‰ a 0.2‰; Fonseca: de 1.8‰ a 0.5‰). Los creadores profesionalizados integran el llamado a la acción como componente implícito del género, ya no como instrucción explícita.</p></li>
<li><p><strong>Estabilidad del <em>bueno</em> como marcador de oralidad performada.</strong> El filler <em>bueno</em> se mantiene estable o crece en la mayoría de los creadores, confirmando su función como bisagra discursiva indispensable para la improvisación organizada que define el registro del vlog.</p></li>
</ol>
</section>
</section>
<section id="la-construcción-del-registro-pragmático-discursivo" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="la-construcción-del-registro-pragmático-discursivo"><span class="header-section-number">7.4</span> La construcción del registro pragmático-discursivo</h2>
<p>Más allá de la variación sociodialectal determinada por el origen geográfico, el análisis transversal del corpus revela que todos los youtubers, independientemente de su procedencia, convergen en un registro pragmático-discursivo común: un modo de hablar diseñado para gestionar la atención, fomentar la interacción y fidelizar comunidades en un entorno de alta competencia algorítmica. Esto es lo que hoy conocemos como la lucha por la economía de la atención.</p>
<section id="léxico-emergente-de-la-intuición-a-la-profesionalización" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="léxico-emergente-de-la-intuición-a-la-profesionalización"><span class="header-section-number">7.4.1</span> Léxico emergente: de la intuición a la profesionalización</h3>
<p>El examen diacrónico del vocabulario empleado entre 2012 y 2016 desmiente la hipótesis de una “jerga adolescente” caótica. Por el contrario, lo que observamos es la consolidación progresiva de un léxico técnico vinculado a la gestión del ecosistema digital.</p>
<p>Esta evolución se manifiesta primero en la saturación del léxico técnico-plataforma Términos como <em>video</em> (presente en el 90% de las producciones finales) y referencias a la interfaz como <em>link</em> o <em>descripción</em> (que ascienden al 55%) dejan de ser instrucciones operativas para convertirse en marcadores deícticos del espacio digital. El youtuber no solo habla <em>en</em> la pantalla, sino <em>sobre</em> la pantalla, espacializando su discurso para guiar la navegación del usuario.</p>
<p>Resulta particularmente revelador el comportamiento de <em>Like/Me gusta</em> y <em>Suscribirse</em>. Lejos de ser adquisición tardía de la profesionalización, los datos indican que son fundacionales: el pedido de aprobación (el <em>like</em>) saturaba el discurso ya en la etapa inicial (55%). La conciencia del algoritmo y la “tiranía del engagement” son constitutivas del género desde su génesis; no se aprende a ser youtuber y <em>luego</em> se pide el like, sino que pedir el like es lo que <em>instituye</em> al sujeto como youtuber.</p>
<p>En segundo lugar, el léxico denota una expansión transmedial. Hacia 2015-2016, el discurso de los creadores registra un incremento masivo en las menciones de plataformas externas como <em>Twitter</em> (+27.5 puntos porcentuales) e <em>Instagram</em> (+20 pp), en detrimento de un <em>Facebook</em> en retroceso (-5 pp). Este desplazamiento léxico no es anecdótico: marca el momento en que el youtuber deja de ser un productor de videos para convertirse en un gestor de comunidades multiplataforma.</p>
<div id="tbl-lexico-plataforma" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lexico-plataforma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;7.3: Evolución de la presencia del léxico de plataforma. Comparativa entre etapa inicial (primeros 5 videos) y final (últimos 5 videos) de los creadores del corpus.
</figcaption>
<div aria-describedby="tbl-lexico-plataforma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Término / Concepto</strong></th>
<th style="text-align: center;"><strong>Etapa Inicial</strong></th>
<th style="text-align: center;"><strong>Etapa Final</strong></th>
<th style="text-align: center;"><strong>Tendencia</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Twitter</td>
<td style="text-align: center;">22.5%</td>
<td style="text-align: center;"><strong>50.0%</strong></td>
<td style="text-align: center;">+27.5 pp ↑</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instagram</td>
<td style="text-align: center;">12.5%</td>
<td style="text-align: center;"><strong>32.5%</strong></td>
<td style="text-align: center;">+20.0 pp ↑</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seguidores</td>
<td style="text-align: center;">10.0%</td>
<td style="text-align: center;"><strong>25.0%</strong></td>
<td style="text-align: center;">+15.0 pp ↑</td>
</tr>
<tr class="even">
<td style="text-align: left;">Link / Descripción</td>
<td style="text-align: center;">47.5%</td>
<td style="text-align: center;"><strong>55.0%</strong></td>
<td style="text-align: center;">+7.5 pp ↑</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suscribirse</td>
<td style="text-align: center;">37.5%</td>
<td style="text-align: center;"><strong>42.5%</strong></td>
<td style="text-align: center;">+5.0 pp ↑</td>
</tr>
<tr class="even">
<td style="text-align: left;">Like / Me gusta</td>
<td style="text-align: center;"><strong>55.0%</strong></td>
<td style="text-align: center;"><strong>57.5%</strong></td>
<td style="text-align: center;">+2.5 pp →</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Facebook</td>
<td style="text-align: center;">30.0%</td>
<td style="text-align: center;"><strong>25.0%</strong></td>
<td style="text-align: center;">-5.0 pp ↓</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La evolución en el CTA (<em>Call to Action</em>) muestra también una maduración comunicativa: la complejidad del pedido desciende levemente (de 2.35 a 1.93 tipos de pedidos por video). En lugar de disparar una ráfaga de órdenes, el youtuber profesional focaliza —elige una acción prioritaria por video— y contextualiza: el pedido se integra a la narrativa (“Si quieren que haga la segunda parte, revienten el botón de like”) en lugar de aparecer como un bloque aislado.</p>
</section>
<section id="la-ritualización-de-la-interacción" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="la-ritualización-de-la-interacción"><span class="header-section-number">7.4.2</span> La ritualización de la interacción</h3>
<p>El análisis del corpus demuestra que el videoblog no sigue las normas de la conversación natural —regidas por la cortesía y el intercambio de turnos— sino una lógica de retención y conversión dictada por el algoritmo.</p>
<div id="tbl-componentes-rituales" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-componentes-rituales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;7.4: Presencia de componentes rituales en el corpus.
</figcaption>
<div aria-describedby="tbl-componentes-rituales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Componente Ritual</strong></th>
<th style="text-align: center;"><strong>Presencia</strong></th>
<th style="text-align: center;"><strong>Porcentaje</strong></th>
<th style="text-align: left;"><strong>Función</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Presentación del Tema</td>
<td style="text-align: center;">65/80</td>
<td style="text-align: center;"><strong>81.2%</strong></td>
<td style="text-align: left;">Componente obligatorio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Llamado a la Acción (CTA)</td>
<td style="text-align: center;">61/80</td>
<td style="text-align: center;"><strong>76.2%</strong></td>
<td style="text-align: left;">Componente estructural</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saludo Verbal</td>
<td style="text-align: center;">47/80</td>
<td style="text-align: center;"><strong>58.8%</strong></td>
<td style="text-align: left;">Componente estilístico</td>
</tr>
<tr class="even">
<td style="text-align: left;">Despedida Verbal</td>
<td style="text-align: center;">47/80</td>
<td style="text-align: center;"><strong>58.8%</strong></td>
<td style="text-align: left;">Componente estilístico</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intro / Branding Verbal</td>
<td style="text-align: center;">16/80</td>
<td style="text-align: center;"><strong>20.0%</strong></td>
<td style="text-align: left;">Componente opcional</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La <strong>Contextualización o Presentación del Tema</strong> emerge como el componente obligatorio por excelencia (81.2%): el enunciador explicita la promesa narrativa en el primer minuto para evitar el <em>zapping</em>. El <strong>Llamado a la Acción</strong> (76.2%) confirma que el pedido de <em>engagement</em> no es un accesorio comercial, sino un componente estructural del género: el vlog está diseñado pragmáticamente para <em>hacer hacer</em> —suscribirse, comentar— tanto como para <em>hacer saber</em>.</p>
<p>Por el contrario, los rituales de cortesía tradicional —Saludo y Despedida verbal— muestran mayor volatilidad (58.8%). Esta elisión no debe interpretarse como descortesía, sino como una adaptación al ritmo acelerado del consumo digital: los inicios <em>in media res</em> y los cortes abruptos al final privilegian la dinámica de la acción sobre el protocolo del encuentro. Más reveladora aún es la escasa presencia de auto-presentaciones (“Hola, soy X”, solo en el 20% de los videos): en una relación de intimidad simulada, re-presentarse sería una redundancia que rompería la ilusión de familiaridad preexistente. El youtuber asume que ya es conocido; su identidad es tácita, dada por el contexto del canal.</p>
</section>
<section id="la-gestión-de-la-periodicidad-la-disculpa-como-evento-de-excepción" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="la-gestión-de-la-periodicidad-la-disculpa-como-evento-de-excepción"><span class="header-section-number">7.4.3</span> La gestión de la periodicidad: la disculpa como evento de excepción</h3>
<p>Dentro de los rituales de mantenimiento del vínculo, la “disculpa por ausencia” es un acto de habla que destacamos como central para reparar rupturas en la periodicidad <span class="citation" data-cites="depiero2013">(<a href="referencias.html#ref-depiero2013" role="doc-biblioref">De Piero, 2012</a>)</span>. Sin embargo, la evidencia empírica del corpus matiza esta centralidad: la disculpa explícita es estadísticamente marginal. Esto sugiere que, en el período 2012-2016, la presión por la regularidad estricta aún no había alcanzado la rigidez posterior, o que los creadores optaban por elidir el conflicto para sostener un tono de entretenimiento puro.</p>
<p>No obstante, cuando la disculpa emerge —como se observa en el caso de Elchuiuical—, despliega una estructura canónica de <strong>reparación de imagen</strong>: reconocimiento de la falta (“perdón por no subir”), derivación de la responsabilidad hacia factores externos (“se rompió la cámara”) y restauración performativa del flujo mediante la entrega del nuevo contenido. En un video de 2015, Elchuiuical abre con una secuencia que ilustra esta estructura:</p>
<blockquote class="blockquote">
<p>«Para empezar, gente, quiero pedirles perdón, los últimos días no subí ningún vídeo. Lo que pasa es que estaba enfermo, no me sentía bien para grabar.» (0:03-0:09)</p>
</blockquote>
<p>La disculpa no es un acto comunicativo menor: es una performance de rendición de cuentas ante la comunidad que implica —y por tanto construye— un contrato de regularidad. La excusa (“estaba enfermo”) humaniza al creador al mismo tiempo que legitima la periodicidad como norma del género. Aunque cuantitativamente minoritario, este ritual funciona como un “evento saliente” en la memoria de la comunidad: marca los momentos de crisis y reafirma la vigencia del contrato de lectura precisamente al señalar su transgresión momentánea.</p>
</section>
<section id="el-agradecimiento-performativo-y-la-consagración-del-número" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="el-agradecimiento-performativo-y-la-consagración-del-número"><span class="header-section-number">7.4.4</span> El agradecimiento performativo y la consagración del número</h3>
<p>Si la disculpa gestiona la falta, el agradecimiento gestiona el exceso: el crecimiento exponencial de la audiencia. En el corpus, el agradecimiento no se dirige al vacío, sino que celebra la capitalización de la fama en cifras tangibles. El caso de Elchuiuical ilustra meridianamente esta operación. En su video “Especial 3000 suscriptores” (2014), la celebración del número organiza la totalidad del video:</p>
<blockquote class="blockquote">
<p>«¡Hola gente! ¿Cómo están mis queridos amigos? ¡Estamos acá en la especial 3000! Y chicos, estamos acá en la especial 3000 porque, vamos […] así que bueno, muchas gracias a todos por suscribirse y vamos por más.» (0:13-0:28)</p>
</blockquote>
<p>El uso del plural inclusivo (“estamos”) opera una distribución retórica del éxito: el logro individual del youtuber se reescribe como una conquista colectiva, fortaleciendo la reciprocidad imaginada. La redundancia enfática (“la especial 3000”, repetida dos veces) revela que el número, en la economía simbólica de la plataforma, funciona como consagración cuantificable de valor social <span class="citation" data-cites="vandijck2013">(<a href="referencias.html#ref-vandijck2013" role="doc-biblioref">Dijck, 2013</a>)</span>. Por su parte, Mica Suárez despliega una variante más afectiva: agradece no el número, sino la fidelidad interaccional (“gracias por ver hasta el final”). En ambos casos, el agradecimiento sella la transacción afectiva del vlog: el youtuber entrega entretenimiento, la audiencia entrega tiempo y atención, y la gratitud verbalizada cierra el circuito.</p>
</section>
<section id="estrategias-de-cortesía-de-la-transgresión-rebelde-a-la-marca-profesional" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="estrategias-de-cortesía-de-la-transgresión-rebelde-a-la-marca-profesional"><span class="header-section-number">7.4.5</span> Estrategias de cortesía: de la transgresión rebelde a la marca profesional</h3>
<p>El análisis pragmático revela una tensión constante entre las normas de la cortesía formal adulta y las dinámicas de afiliación entre pares. Lejos de ser estático, este registro evoluciona a lo largo del período, transitando desde una anticortesía rebelde —propia de la etapa amateur— hacia una cortesía profesionalizada y atenta a las normas de comunidad.</p>
<p>Siguiendo los planteos de <span class="citation" data-cites="palazzo2010b">Palazzo (<a href="referencias.html#ref-palazzo2010b" role="doc-biblioref">2009</a>)</span>, el uso de vocabulario vulgar y palabras tabú en el discurso juvenil no opera necesariamente como agresión, sino como una estrategia paradójica de afiliación que marca distancia respecto del registro institucional escolar. Sin embargo, los datos del corpus evidencian una tendencia decreciente en esta práctica: la densidad de insultos cae de 8.19 términos cada mil palabras en la etapa inicial a 6.08 en la etapa final. Esta atenuación progresiva no implica la desaparición de la “suciedad” léxica, sino su refuncionalización: a medida que el canal se profesionaliza, el youtuber reserva la anticortesía para momentos de énfasis cómico o catarsis controlada.</p>
<p>Una meta-reflexión del propio corpus ilumina esta dinámica. En VID 49, Mariano Bondar y Lucas Castel recuerdan juntos sus primeros videos:</p>
<blockquote class="blockquote">
<p>“Aparte, en ese momento, chabón, este primer video, me acuerdo que… que me quería, o sea, hablaba bajito porque no quería que venga nadie a ver que estaba haciendo.” — Bondar<br>
“Yo era igual, yo era igual, eso es un factor que se repite en todos, boludo.” — Castel (VID 49, 2:20-2:30)</p>
</blockquote>
<p>El “hablaba bajito” de Bondar revela que el registro del vlog no nace como grito, sino como susurro clandestino: el youtuber incipiente negocia su voz no solo con la audiencia, sino con el espacio doméstico que habita. El “eso es un factor que se repite en todos” de Castel convierte la anécdota en dato sociolingüístico: la modulación del volumen en función del entorno físico es una experiencia generacional compartida. El registro del vlog, entonces, no se “aprende” de otros youtubers, sino que emerge de las condiciones materiales del dormitorio adolescente.</p>
<p>Contrariamente a la expectativa de encontrar fragmentación de la audiencia en “tribus” con nombres exclusivos (como los “Serranistas”, cuya aparición en el corpus es marginal), la estrategia predominante de afiliación es genérica y horizontal. El vocativo por excelencia es <strong>“Chicos”</strong> (53 apariciones), un término inclusivo y generacionalmente marcado que evita las jerarquías implícitas en la relación ídolo-fan. Esta horizontalidad se refuerza mediante el uso sistemático del <strong>“nosotros” inclusivo</strong> (48 apariciones): verbos como “vamos a ver” o “nos pasa” construyen la ficción de una experiencia compartida, borrando discursivamente la asimetría estructural entre quien produce el video y quien lo consume.</p>
<p>En cuanto a la gestión de la imagen, la tensión entre “ser uno mismo” y “actuar para la cámara” se resuelve mediante estilos diferenciados. En el caso de Mica Suárez se observa mayor frecuencia de léxico emocional (tristeza, miedo, sentir), legitimando la vulnerabilidad como insumo narrativo. En contraste, perfiles como el de Lionel Ferro construyen su autenticidad desde la destreza escénica y el <em>timing</em> cómico, donde la espontaneidad se percibe paradójicamente a través de una actuación controlada. Ambos estilos demuestran que no existe una única forma de ser auténtico en YouTube, sino repertorios discursivos situados que gestionan la imagen del yo ante la mirada masiva.</p>
</section>
</section>
<section id="del-mito-de-la-variedad-web-al-registro-situado" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="del-mito-de-la-variedad-web-al-registro-situado"><span class="header-section-number">7.5</span> Del mito de la variedad web al registro situado</h2>
<p>Los análisis precedentes permiten retomar la pregunta inicial con una base empírica sólida: ¿estamos ante el surgimiento de una “variedad web” del español en YouTube, o asistimos a fenómenos de otra naturaleza?</p>
<p>La evidencia cuantitativa y cualitativa del corpus no ofrece respaldo para sostener la existencia de una variedad lingüística autónoma. No existen innovaciones estructurales profundas: la sintaxis y los rasgos fonéticos (como el yeísmo rehilado o la aspiración de /s/) corresponden inequívocamente a las variedades regionales del español argentino ya descriptas. Los youtubers no cambian su gramática al encender la cámara; simplemente la ponen en escena. El léxico específico tampoco constituye un sistema complejo: se limita funcionalmente a verbos de acción en plataforma (<em>suscribirse</em>, <em>comentar</em>), sustantivos de interfaz (<em>link</em>, <em>descripción</em>) y préstamos tecnológicos (<em>like</em>). En coincidencia con <span class="citation" data-cites="cerruti2013">Cerruti &amp; Onesti (<a href="referencias.html#ref-cerruti2013" role="doc-biblioref">2013</a>)</span>, podemos afirmar que hablar de “variedad digital” es un error categorial.</p>
<p>La categoría teórica más robusta para explicar los hallazgos es la de <strong>registro</strong> <span class="citation" data-cites="halliday1978">(<a href="referencias.html#ref-halliday1978" role="doc-biblioref">Halliday, 1978</a>)</span>: una variación funcional del lenguaje determinada por el uso. Las regularidades observadas en los 80 videos responden a tres variables situacionales. El Campo (tema) define una narrativa centrada en la intimidad y el entretenimiento. El Tenor (relación) presenta la particularidad de performarse discursivamente como horizontal pese a ser estructuralmente asimétrico: el uso masivo de “Chicos” y del “Nosotros” inclusivo construye una “masa amiga” borrando las jerarquías implícitas de la fama. El Modo (canal) genera lo que podemos denominar una <strong>deixis de pantalla</strong>: el crecimiento de expresiones como “acá abajo”, “en el link” o “te dejo la foto acá” evidencia cómo el discurso se ancla en la interfaz visual.</p>
<p>En última instancia, este análisis sugiere la necesidad de “des-tecnologizar” la mirada sobre el lenguaje juvenil. Muchos rasgos frecuentemente atribuidos a “Internet” o a “YouTube” son, en realidad, marcas de estilo juvenil amplificadas por el medio. La informalidad, la ironía y la alta emocionalidad validada en el corpus no son “ciberlengua”; son estrategias generacionales de diferenciación frente al mundo adulto y sus instituciones. Los sujetos de esta tesis no hablan como máquinas ni como algoritmos; hablan como jóvenes argentinos que han profesionalizado un registro técnico-comercial para gestionar su audiencia, insertando su voz local en una conversación global.</p>
</section>
<section id="conclusiones-parciales-del-capítulo" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="conclusiones-parciales-del-capítulo"><span class="header-section-number">7.6</span> Conclusiones parciales del capítulo</h2>
<p>El recorrido analítico permite clausurar la pregunta por la naturaleza del lenguaje en el videoblog con una afirmación: no estamos ante el surgimiento de una nueva “variedad dialectal” de Internet, sino ante la consolidación de un <strong>registro profesional situado</strong>. Lejos de la improvisación caótica que a menudo se atribuye al habla juvenil, los datos revelan que el lenguaje de los youtubers es una construcción pragmática, diseñada para gestionar la atención, la identidad y el mercado en un entorno de alta competencia simbólica.</p>
<p>La evidencia empírica desarticula la hipótesis de la “variedad web”. Los youtubers no utilizan una gramática ni una fonología nativa de lo digital; operan mediante un registro pragmático-discursivo caracterizado por su funcionalidad: léxico técnico restringido orientado a la gestión de la interfaz, y ritualización de la interacción que prioriza la eficacia algorítmica sobre el protocolo social. La evolución desde una anticortesía transgresora hacia una cortesía profesionalizada demuestra que la “extimidad” lingüística ha dejado de ser una catarsis cruda para convertirse en un activo de marca. El insulto y la vulgaridad, otrora marcas de autenticidad rebelde, se atenúan o refuncionalizan para no obstaculizar la expansión de la audiencia.</p>
<p>Quizás el hallazgo sociolingüístico más relevante de la investigación sea la identificación de un patrón estructural de nivelación dialectal hacia el <strong>rioplatense bonaerense</strong>. El análisis de las trayectorias de creadores del interior del país demuestra que la convergencia lingüística hacia el centro no es neutra, sino una estrategia de viabilidad profesional. Esta dinámica revela la persistencia de jerarquías simbólicas tradicionales en el entorno digital: YouTube Argentina no es un espacio plano, sino un territorio estriado donde el prestigio se concentra en Buenos Aires. Sin embargo, esta operación no implica una pérdida absoluta de identidad, sino una negociación glocal: se neutraliza la <em>forma</em> (fonética y gramática) para asegurar el alcance, pero se enfatiza el <em>contenido</em> local (referencias culturales, narrativas de origen) para preservar la autenticidad.</p>
<p>Las limitaciones del estudio merecen reconocimiento. El sesgo centralista y de género del corpus —con predominancia de varones y habitantes del AMBA— no es solo una limitación metodológica, sino un dato de la realidad del campo en el período 2012-2016: la visibilidad algorítmica reproducía desigualdades estructurales preexistentes. Investigaciones futuras deberán indagar si la explosión posterior de plataformas como TikTok ha democratizado estos flujos o si ha generado nuevas hegemonías. Asimismo, la naturaleza ortográfica de las transcripciones impone un límite al análisis fonético fino: un abordaje acústico instrumental constituiría el paso necesario para medir con precisión los grados de acomodación dialectal que aquí hemos descrito cualitativamente.</p>
<p>En definitiva, el youtuber no es un usuario pasivo de una jerga de moda, sino un auténtico agente sociolingüístico: su habla es el resultado de una relación dialógica constante entre la espontaneidad generacional y la disciplina del medio. La nivelación dialectal y la adopción del registro técnico no deben leerse con nostalgia purista, como una degradación de la diversidad, sino pragmáticamente como tecnologías de ascenso social y posicionamiento público. Los jóvenes argentinos han logrado convertir la conversación cotidiana —esa materia prima aparentemente trivial— en un producto cultural masivo, y para hacerlo han debido profesionalizar su lengua. Estudiar sus prácticas discursivas es comprender la vanguardia de los procesos mediante los cuales las nuevas generaciones habitan, negocian y transforman el espacio público contemporáneo.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-alcantara2016" class="csl-entry" role="listitem">
Alcántara Plá, M. (2016). Neologismos tecnol<span>ó</span>gicos y nuevos comportamientos en la sociedad red. <em>Aposta. Revista de Ciencias Sociales</em>, <em>69</em>, 14–38.
</div>
<div id="ref-androutsopoulos2013" class="csl-entry" role="listitem">
Androutsopoulos, J. (2013). Code-switching in computer-mediated communication. In S. C. Herring, D. Stein, &amp; T. Virtanen (Eds.), <em>Handbook of pragmatics of computer-mediated communication</em> (pp. 667–694). de Gruyter Mouton. <a href="https://doi.org/10.1515/9783110214468.667">https://doi.org/10.1515/9783110214468.667</a>
</div>
<div id="ref-cerruti2013" class="csl-entry" role="listitem">
Cerruti, M., &amp; Onesti, C. (2013). Netspeak: A language variety? Some remarks from an italian sociolinguistic perspective. In E. Miola (Ed.), <em>Languages go. Web. Standard and non standard languages on the internet</em> (pp. 23–39). Edizioni dell’Orso.
</div>
<div id="ref-crystal2002" class="csl-entry" role="listitem">
Crystal, D. (2001). <em>Language and the internet</em>. Cambridge University Press.
</div>
<div id="ref-depiero2013" class="csl-entry" role="listitem">
De Piero, J. L. (2012). <em>Las comunidades lingüísticas en los vlogs de YouTube: Estudio contrastivo de casos</em> [Tesis de Licenciatura en Letras]. Universidad Nacional de Tucumán, Facultad de Filosofía y Letras.
</div>
<div id="ref-vandijck2013" class="csl-entry" role="listitem">
Dijck, J. van. (2013). <em>The culture of connectivity: A critical history of social media</em>. Oxford University Press.
</div>
<div id="ref-fasold1996" class="csl-entry" role="listitem">
Fasold, R. (1990). <em>The sociolinguistics of language</em>. Basil Blackwell.
</div>
<div id="ref-feixa2006" class="csl-entry" role="listitem">
Feixa, C. (2006). <em>De j<span>ó</span>venes, bandas y tribus. Antropolog<span>í</span>a de la juventud</em> (3rd ed.). Ariel.
</div>
<div id="ref-fontanella2004" class="csl-entry" role="listitem">
Fontanella de Weinberg, M. B. (2004). <em>El espa<span>ñ</span>ol de am<span>é</span>rica</em> (3rd ed.). Ediciones Larousse / Mapfre.
</div>
<div id="ref-garciacanclini1995" class="csl-entry" role="listitem">
García Canclini, N. (1995). <em>Hybrid cultures: Strategies for entering and leaving modernity</em>. University of Minnesota Press.
</div>
<div id="ref-giammatteo2012" class="csl-entry" role="listitem">
Giammatteo, M., &amp; Albano, H. (Eds.). (2012). <em>El l<span>é</span>xico: De la vida cotidiana a la comunicaci<span>ó</span>n cibern<span>é</span>tica</em>. Biblos.
</div>
<div id="ref-halliday1978" class="csl-entry" role="listitem">
Halliday, M. A. K. (1978). <em>Language as social semiotic: The social interpretation of language and meaning</em>. Edward Arnold.
</div>
<div id="ref-moreno1999" class="csl-entry" role="listitem">
Moreno Fernández, F. (1999). <em>Principios de socioling<span>ü</span><span>í</span>stica y sociolog<span>í</span>a del lenguaje</em>. Ariel.
</div>
<div id="ref-palazzo2010b" class="csl-entry" role="listitem">
Palazzo, M. G. (2009). El ciberdiscurso juvenil: Representaciones sociales del desconcierto, la censura y la aceptaci<span>ó</span>n. <em>Esp<span>é</span>culo. Revista de Estudios Literarios</em>, <em>41</em>. <a href="https://webs.ucm.es/info/especulo/numero41/">https://webs.ucm.es/info/especulo/numero41/</a>
</div>
<div id="ref-palazzo2010a" class="csl-entry" role="listitem">
Palazzo, M. G. (2010). Aspectos comunicativos del ciberdiscurso juvenil. Consideraciones te<span>ó</span>ricas. <em>Revista Argentina de Estudios de Juventud</em>, 1–22. <a href="https://www.aacademica.org/gabriela.palazzo/59">https://www.aacademica.org/gabriela.palazzo/59</a>
</div>
<div id="ref-robertson1995" class="csl-entry" role="listitem">
Robertson, R. (1995). Glocalization: Time-space and homogeneity-heterogeneity. In M. Featherstone, S. Lash, &amp; R. Robertson (Eds.), <em>Global modernities</em> (pp. 25–44). SAGE Publications.
</div>
<div id="ref-schneider2008" class="csl-entry" role="listitem">
Schneider, J., &amp; Foot, K. (2007). <em>Web campaigning</em>. MIT Press.
</div>
<div id="ref-thurlow2011" class="csl-entry" role="listitem">
Thurlow, C., &amp; Mroczek, K. (2011). Introduction: Fresh perspectives on new media sociolinguistics. In C. Thurlow &amp; K. Mroczek (Eds.), <em>Digital discourse: Language in the new media</em>. Oxford University Press.
</div>
<div id="ref-trudgill2007" class="csl-entry" role="listitem">
Trudgill, P. (2000). <em>Sociolinguistics: An introduction to language and society</em> (4th ed.). Penguin Books.
</div>
<div id="ref-vidal1964" class="csl-entry" role="listitem">
Vidal de Battini, B. E. (1964). <em>El espa<span>ñ</span>ol de la argentina</em>. Consejo Nacional de Educaci<span>ó</span>n.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06_trayectorias.html" class="pagination-link" aria-label="Trayectorias identitarias en el videoblog juvenil">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Trayectorias identitarias en el videoblog juvenil</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08_conclusiones.html" class="pagination-link" aria-label="Conclusiones">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conclusiones</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>